# Generated by Django 4.2.6 on 2026-03-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from name if not provided)', max_length=100, null=True),
        ),
    ]
