# Generated by Django 4.2.6 on 2026-03-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_alter_dashboard_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dashboard',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='slug',
        ),
    ]
