# Generated by Django 4.2.6 on 2026-01-23 04:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProofOfDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("erp_id", models.IntegerField(blank=True, default=None, null=True)),
                ("erp_code", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "created_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "created_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "modified_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("modified_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "is_deleted",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "authorized_level",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "authorized_by_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "authorized_by_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("authorized_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "current_authorized_level",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "current_authorized_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Pending"),
                            (2, "Approved"),
                            (3, "Rejected"),
                            (4, "Skipped"),
                        ],
                        default=1,
                        null=True,
                    ),
                ),
                (
                    "current_authorized_by_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "current_authorized_by_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_authorized_on",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "authorized_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Pending"),
                            (2, "Approved"),
                            (3, "Rejected"),
                            (4, "Skipped"),
                        ],
                        default=4,
                        null=True,
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(db_index=True, default="RETAILER", max_length=20),
                ),
                ("customer_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("pod_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Delivered"),
                            ("FAILED", "Failed Delivery"),
                            ("PARTIAL", "Partial Delivery"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("receiver_name", models.CharField(default="", max_length=120)),
                (
                    "receiver_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be 10 digits",
                                regex="^[0-9]{10}$",
                            )
                        ],
                    ),
                ),
                (
                    "delivered_by",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("delivered_date", models.DateField(default=django.utils.timezone.now)),
                ("remarks", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "proof_of_delivery",
                "ordering": ["-delivered_date"],
            },
        ),
        migrations.CreateModel(
            name="ProofOfDeliveryFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("erp_id", models.IntegerField(blank=True, default=None, null=True)),
                ("erp_code", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "created_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "created_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "modified_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("modified_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "is_deleted",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("file", models.FileField(upload_to="pod/")),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "proof",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="Delivery.proofofdelivery",
                    ),
                ),
            ],
            options={
                "db_table": "proof_of_delivery_file",
                "ordering": ["-created_on"],
            },
        ),
    ]
