# Generated by Django 4.2.6 on 2026-01-23 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Invoice", "0001_initial"),
        ("Delivery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proofofdelivery",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="proofs",
                to="Invoice.invoice",
            ),
        ),
    ]
