# Generated by Django 4.2.6 on 2026-01-23 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Sales", "0001_initial"),
        ("Delivery", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proofofdelivery",
            name="sales_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="proofs",
                to="Sales.salesorder",
            ),
        ),
        migrations.AddIndex(
            model_name="proofofdeliveryfile",
            index=models.Index(fields=["proof"], name="proof_of_de_proof_i_c1d3f5_idx"),
        ),
        migrations.AddIndex(
            model_name="proofofdelivery",
            index=models.Index(
                fields=["invoice"], name="proof_of_de_invoice_c68d49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proofofdelivery",
            index=models.Index(
                fields=["sales_order"], name="proof_of_de_sales_o_aae114_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proofofdelivery",
            index=models.Index(fields=["status"], name="proof_of_de_status_1c4406_idx"),
        ),
        migrations.AddIndex(
            model_name="proofofdelivery",
            index=models.Index(
                fields=["customer_type", "customer_id"],
                name="proof_of_de_custome_1a5b89_idx",
            ),
        ),
    ]
