# Generated by Django 5.0.1 on 2026-01-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Delivery", "0004_alter_proofofdelivery_authorized_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proofofdelivery",
            name="pod_number",
            field=models.CharField(
                db_index=True, max_length=50, null=True, unique=True
            ),
        ),
    ]
