# Generated by Django 5.0.1 on 2026-02-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Delivery", "0005_proofofdelivery_pod_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proofofdelivery",
            name="delivered_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="proofofdelivery",
            name="receiver_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="proofofdelivery",
            name="receiver_phone",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
