# Generated by Django 4.2.6 on 2026-01-23 04:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Masters", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "profilepicture",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="profilepicture"
                    ),
                ),
                (
                    "username",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("password", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True, db_index=True, max_length=15, null=True
                    ),
                ),
                ("otp", models.CharField(blank=True, max_length=6, null=True)),
                ("first_name", models.CharField(blank=True, max_length=255)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                (
                    "gender",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "Male"), (2, "Female"), (3, "Others")],
                        null=True,
                    ),
                ),
                (
                    "device_access",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Only Mobile"),
                            (2, "Only Web"),
                            (3, "Both"),
                            (4, "None"),
                        ],
                        default=1,
                        null=True,
                    ),
                ),
                ("is_email_verified", models.BooleanField(default=False)),
                ("is_phone_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("receive_email", models.BooleanField(default=True)),
                ("receive_sms", models.BooleanField(default=True)),
                ("receive_notification", models.BooleanField(default=True)),
                (
                    "created_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "created_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "modified_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "modified_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("erp_id", models.IntegerField(blank=True, default=None, null=True)),
                ("erp_code", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "alternate_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("pincode", models.CharField(blank=True, max_length=10, null=True)),
                ("is_guest", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "channel_partner_type",
                    models.CharField(
                        choices=[
                            ("STAFF", "Staff"),
                            ("SUPERSTOCKIST", "Superstockist"),
                            ("DISTRIBUTOR", "Distributor"),
                            ("RETAILER", "Retailer"),
                        ],
                        default="STAFF",
                        help_text="Type of channel partner this user belongs to",
                        max_length=20,
                    ),
                ),
                (
                    "distributor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assigned distributor (if type is DISTRIBUTOR)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="Masters.distributor",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "retailer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assigned retailer (if type is RETAILER)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="Masters.retailer",
                    ),
                ),
                (
                    "superstockist",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assigned superstockist (if type is SUPERSTOCKIST)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="Masters.superstockist",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
