# Generated by Django 5.2.16 on 2026-08-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="booking_data_scope",
            field=models.CharField(
                choices=[("OWN", "Own"), ("TEAM", "Team"), ("ALL", "All")],
                default="ALL",
                help_text="Data visibility for Bookings",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="followup_data_scope",
            field=models.CharField(
                choices=[("OWN", "Own"), ("TEAM", "Team"), ("ALL", "All")],
                default="ALL",
                help_text="Data visibility for Follow-ups",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="lead_data_scope",
            field=models.CharField(
                choices=[("OWN", "Own"), ("TEAM", "Team"), ("ALL", "All")],
                default="ALL",
                help_text="Data visibility for Leads",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="sitevisit_data_scope",
            field=models.CharField(
                choices=[("OWN", "Own"), ("TEAM", "Team"), ("ALL", "All")],
                default="ALL",
                help_text="Data visibility for Site Visits",
                max_length=10,
            ),
        ),
    ]
