# Generated by Django 5.2.17 on 2026-08-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(
                default=False,
                help_text="Admin users have all permissions without being superuser",
            ),
        ),
    ]
