# Generated by Django 5.0.1 on 2026-01-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Masters", "0003_remove_distributor_distributor_state_active_idx_and_more"),
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="companies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Companies this user has access to",
                related_name="users",
                to="Masters.company",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="has_all_companies",
            field=models.BooleanField(
                default=False, help_text="User has access to all companies"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="has_all_locations",
            field=models.BooleanField(
                default=False, help_text="User has access to all locations"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Locations this user has access to",
                related_name="users",
                to="Masters.location",
            ),
        ),
    ]
