# Generated by Django 5.2.17 on 2026-08-24 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0003_alter_user_booking_data_scope_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissiontemplatedetail",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="Users.permissiontemplate",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="booking_data_scope",
            field=models.CharField(
                choices=[("OWN", "Own"), ("TEAM", "Team"), ("ALL", "All")],
                default="OWN",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bookings",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="followup_data_scope",
            field=models.CharField(
                choices=[("OWN", "Own"), ("TEAM", "Team"), ("ALL", "All")],
                default="OWN",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="joining_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="lead_data_scope",
            field=models.CharField(
                choices=[("OWN", "Own"), ("TEAM", "Team"), ("ALL", "All")],
                default="OWN",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="leads_assigned",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="must_reset_password",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="registrations",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="site_visits",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="sitevisit_data_scope",
            field=models.CharField(
                choices=[("OWN", "Own"), ("TEAM", "Team"), ("ALL", "All")],
                default="OWN",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("SUSPENDED", "Suspended"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userpermission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="screen_permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
