# Generated by Django 5.2.16 on 2026-07-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_permissiontemplate_screen_remove_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookings',
            field=models.PositiveIntegerField(default=0, help_text='Total bookings'),
        ),
        migrations.AddField(
            model_name='user',
            name='joining_date',
            field=models.DateField(blank=True, help_text='Employee joining date', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='leads_assigned',
            field=models.PositiveIntegerField(default=0, help_text='Total leads assigned'),
        ),
        migrations.AddField(
            model_name='user',
            name='registrations',
            field=models.PositiveIntegerField(default=0, help_text='Total registrations'),
        ),
        migrations.AddField(
            model_name='user',
            name='site_visits',
            field=models.PositiveIntegerField(default=0, help_text='Total site visits'),
        ),
    ]
