# Generated by Django 5.0.1 on 2026-01-30 05:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Masters", "0002_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="distributor",
            name="distributor_state_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="distributor",
            name="distributor_parent_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="item",
            name="item_name_idx",
        ),
        migrations.RemoveIndex(
            model_name="item",
            name="item_active_saleable_idx",
        ),
        migrations.RemoveIndex(
            model_name="pricebook",
            name="pricebook_lookup_idx",
        ),
        migrations.RemoveIndex(
            model_name="pricebook",
            name="pricebook_location_idx",
        ),
        migrations.RemoveIndex(
            model_name="pricebook",
            name="pricebook_partner_idx",
        ),
        migrations.RemoveIndex(
            model_name="retailer",
            name="retailer_state_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="retailer",
            name="retailer_parent_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="superstockist",
            name="superstockist_state_active_idx",
        ),
    ]
