# Generated by Django 5.0.1 on 2026-02-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Masters", "0003_remove_distributor_distributor_state_active_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="pan_number",
            field=models.CharField(
                blank=True,
                help_text="Company PAN Number (10 characters)",
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
    ]
