# Generated by Django 5.0.1 on 2026-02-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Masters", "0004_company_pan_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="contact_person_2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="contact_person_3",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="email_2",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="email_3",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="phone_2",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="phone_3",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
