# Generated by Django 5.0.1 on 2026-02-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Masters",
            "0005_location_contact_person_2_location_contact_person_3_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="distributor",
            name="contact_person_2",
            field=models.CharField(
                blank=True,
                help_text="Secondary contact person",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="distributor",
            name="email_2",
            field=models.EmailField(
                blank=True,
                help_text="Secondary contact email",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="distributor",
            name="phone_2",
            field=models.CharField(
                blank=True,
                help_text="Secondary contact phone number",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="contact_person_2",
            field=models.CharField(
                blank=True,
                help_text="Secondary contact person",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="email_2",
            field=models.EmailField(
                blank=True,
                help_text="Secondary contact email",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="phone_2",
            field=models.CharField(
                blank=True,
                help_text="Secondary contact phone number",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="superstockist",
            name="contact_person_2",
            field=models.CharField(
                blank=True,
                help_text="Secondary contact person",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="superstockist",
            name="email_2",
            field=models.EmailField(
                blank=True,
                help_text="Secondary contact email",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="superstockist",
            name="phone_2",
            field=models.CharField(
                blank=True,
                help_text="Secondary contact phone number",
                max_length=15,
                null=True,
            ),
        ),
    ]
