# Generated by Django 5.0.1 on 2026-02-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Masters", "0006_distributor_contact_person_2_distributor_email_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="distributor",
            name="mobile_2",
            field=models.CharField(
                blank=True,
                help_text="Secondary mobile number",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="mobile_2",
            field=models.CharField(
                blank=True,
                help_text="Secondary mobile number",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="superstockist",
            name="mobile_2",
            field=models.CharField(
                blank=True,
                help_text="Secondary mobile number",
                max_length=15,
                null=True,
            ),
        ),
    ]
