# Generated by Django 5.0.1 on 2026-02-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Masters", "0007_distributor_mobile_2_retailer_mobile_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="distributor",
            name="aadhar",
            field=models.CharField(
                blank=True,
                help_text="Aadhar Number (12 digits)",
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="distributor",
            name="bank_account_number",
            field=models.CharField(
                blank=True, help_text="Bank account number", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="distributor",
            name="bank_account_type",
            field=models.CharField(
                blank=True,
                choices=[("SAVINGS", "Savings"), ("CURRENT", "Current")],
                help_text="Account type",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="distributor",
            name="bank_branch",
            field=models.CharField(
                blank=True, help_text="Bank branch", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="distributor",
            name="bank_ifsc",
            field=models.CharField(
                blank=True, help_text="IFSC code", max_length=11, null=True
            ),
        ),
        migrations.AddField(
            model_name="distributor",
            name="bank_name",
            field=models.CharField(
                blank=True, help_text="Bank name", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="distributor",
            name="google_location",
            field=models.TextField(
                blank=True, help_text="Google Maps location URL", null=True
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="aadhar",
            field=models.CharField(
                blank=True,
                help_text="Aadhar Number (12 digits)",
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="bank_account_number",
            field=models.CharField(
                blank=True, help_text="Bank account number", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="bank_account_type",
            field=models.CharField(
                blank=True,
                choices=[("SAVINGS", "Savings"), ("CURRENT", "Current")],
                help_text="Account type",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="bank_branch",
            field=models.CharField(
                blank=True, help_text="Bank branch", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="bank_ifsc",
            field=models.CharField(
                blank=True, help_text="IFSC code", max_length=11, null=True
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="bank_name",
            field=models.CharField(
                blank=True, help_text="Bank name", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="google_location",
            field=models.TextField(
                blank=True, help_text="Google Maps location URL", null=True
            ),
        ),
        migrations.AddField(
            model_name="superstockist",
            name="aadhar",
            field=models.CharField(
                blank=True,
                help_text="Aadhar Number (12 digits)",
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="superstockist",
            name="bank_account_number",
            field=models.CharField(
                blank=True, help_text="Bank account number", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="superstockist",
            name="bank_account_type",
            field=models.CharField(
                blank=True,
                choices=[("SAVINGS", "Savings"), ("CURRENT", "Current")],
                help_text="Account type",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="superstockist",
            name="bank_branch",
            field=models.CharField(
                blank=True, help_text="Bank branch", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="superstockist",
            name="bank_ifsc",
            field=models.CharField(
                blank=True, help_text="IFSC code", max_length=11, null=True
            ),
        ),
        migrations.AddField(
            model_name="superstockist",
            name="bank_name",
            field=models.CharField(
                blank=True, help_text="Bank name", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="superstockist",
            name="google_location",
            field=models.TextField(
                blank=True, help_text="Google Maps location URL", null=True
            ),
        ),
    ]
