# Generated by Django 5.0.1 on 2026-02-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Masters", "0009_channelpartnerattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelpartnerattachment",
            name="original_filename",
            field=models.CharField(
                blank=True, help_text="Original filename", max_length=255, null=True
            ),
        ),
    ]
