# Generated by Django 5.0.1 on 2026-02-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Masters", "0010_add_original_filename_to_attachments"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="pincode",
            field=models.CharField(
                blank=True, help_text="PIN Code", max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="pincode",
            field=models.CharField(
                blank=True, help_text="PIN Code", max_length=10, null=True
            ),
        ),
    ]
