# Generated by Django 5.0.1 on 2026-02-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Masters", "0011_add_pincode_to_city_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricebookdocument",
            name="authorized_by_identifier",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pricebookdocument",
            name="authorized_by_type",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="pricebookdocument",
            name="authorized_level",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="pricebookdocument",
            name="authorized_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="pricebookdocument",
            name="authorized_status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")],
                default=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pricebookdocument",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="pricebookdocument",
            name="current_authorized_by_identifier",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pricebookdocument",
            name="current_authorized_by_type",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="pricebookdocument",
            name="current_authorized_level",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="pricebookdocument",
            name="current_authorized_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="pricebookdocument",
            name="current_authorized_status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")],
                default=1,
                null=True,
            ),
        ),
    ]
