# Generated by Django 5.0.1 on 2026-02-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Masters", "0012_pricebookdocument_authorized_by_identifier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="distributor",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="outlettype",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="pricebook",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="superstockist",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="tax",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="uom",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
