# Generated by Django 5.0.1 on 2026-02-09 10:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Masters", "0013_alter_brand_code_alter_category_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scheme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("erp_id", models.IntegerField(blank=True, default=None, null=True)),
                ("erp_code", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "created_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "created_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "modified_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("modified_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "is_deleted",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "authorized_level",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "authorized_by_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "authorized_by_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("authorized_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "current_authorized_level",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "current_authorized_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")],
                        default=1,
                        null=True,
                    ),
                ),
                (
                    "current_authorized_by_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "current_authorized_by_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_authorized_on",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "authorized_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")],
                        default=1,
                        null=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique scheme code", max_length=50, unique=True
                    ),
                ),
                ("name", models.CharField(help_text="Scheme name", max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed scheme description"
                    ),
                ),
                (
                    "scheme_type",
                    models.CharField(
                        choices=[
                            ("QUANTITY", "Quantity Based"),
                            ("VALUE", "Value Based"),
                            ("COMBO", "Combo Offer"),
                            ("SLAB", "Slab Based"),
                            ("FLAT", "Flat Discount"),
                        ],
                        help_text="Type of scheme",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="DRAFT",
                        help_text="Scheme status",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher number = Higher Priority (0-100)"
                    ),
                ),
                (
                    "is_stackable",
                    models.BooleanField(
                        default=False, help_text="Can combine with other schemes"
                    ),
                ),
                (
                    "max_applications",
                    models.IntegerField(
                        blank=True,
                        help_text="Max times scheme can apply in single order",
                        null=True,
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(help_text="Scheme effective from date"),
                ),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="Scheme effective to date (null = no end date)",
                        null=True,
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum discount amount for this scheme",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "min_order_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum order value to apply this scheme",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False, help_text="Scheme requires approval to activate"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, help_text="When scheme was approved", null=True
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_schemes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this scheme belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schemes",
                        to="Masters.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheme",
                "verbose_name_plural": "Schemes",
                "db_table": "scheme",
                "ordering": ["-priority", "-created_on"],
            },
        ),
        migrations.CreateModel(
            name="SchemeApplicability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("ALL", "All"),
                            ("RETAILER", "Retailer"),
                            ("DISTRIBUTOR", "Distributor"),
                            ("SUPERSTOCKIST", "Superstockist"),
                        ],
                        default="ALL",
                        help_text="Type of customer",
                        max_length=20,
                    ),
                ),
                (
                    "apply_to_all",
                    models.BooleanField(
                        default=True, help_text="Apply to all matching customers"
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        help_text="Area for geographic targeting",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Masters.area",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        help_text="City for geographic targeting",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Masters.city",
                    ),
                ),
                (
                    "distributor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific distributor",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Masters.distributor",
                    ),
                ),
                (
                    "retailer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific retailer",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Masters.retailer",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicability",
                        to="Masters.scheme",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        help_text="State for geographic targeting",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Masters.state",
                    ),
                ),
                (
                    "superstockist",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific superstockist",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Masters.superstockist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheme Applicability",
                "verbose_name_plural": "Scheme Applicability",
                "db_table": "scheme_applicability",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SchemeBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "benefit_type",
                    models.CharField(
                        choices=[
                            ("DISCOUNT_PERCENTAGE", "Discount %"),
                            ("DISCOUNT_AMOUNT", "Discount Amount"),
                            ("FREE_ITEM", "Free Item"),
                            ("FREE_QUANTITY", "Free Quantity"),
                            ("CASHBACK", "Cashback"),
                        ],
                        help_text="Type of benefit",
                        max_length=30,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Discount % or amount depending on type",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum discount for this benefit",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "free_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Quantity of free item",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "apply_to_all",
                    models.BooleanField(
                        default=False, help_text="Apply benefit to all items in order"
                    ),
                ),
                (
                    "apply_to_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefit_targets",
                        to="Masters.category",
                    ),
                ),
                (
                    "apply_to_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefit_targets",
                        to="Masters.item",
                    ),
                ),
                (
                    "free_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheme_free_items",
                        to="Masters.item",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefits",
                        to="Masters.scheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheme Benefit",
                "verbose_name_plural": "Scheme Benefits",
                "db_table": "scheme_benefit",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SchemeCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("MIN_QUANTITY", "Minimum Quantity"),
                            ("MIN_VALUE", "Minimum Value"),
                            ("EXACT_QUANTITY", "Exact Quantity"),
                            ("QUANTITY_RANGE", "Quantity Range"),
                            ("VALUE_RANGE", "Value Range"),
                            ("ITEM_COMBO", "Item Combination"),
                        ],
                        help_text="Type of condition",
                        max_length=30,
                    ),
                ),
                (
                    "value_from",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum value or range start",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "value_to",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum value (for range conditions)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "logical_operator",
                    models.CharField(
                        choices=[("AND", "AND"), ("OR", "OR")],
                        default="AND",
                        help_text="Logical operator for multiple conditions",
                        max_length=3,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Category for category-specific conditions",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Masters.category",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Item for item-specific conditions",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Masters.item",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="Masters.scheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheme Condition",
                "verbose_name_plural": "Scheme Conditions",
                "db_table": "scheme_condition",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SchemeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("UPDATED", "Updated"),
                            ("ACTIVATED", "Activated"),
                            ("DEACTIVATED", "Deactivated"),
                            ("DELETED", "Deleted"),
                        ],
                        help_text="Action performed",
                        max_length=20,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True, default=dict, help_text="JSON of changes made"
                    ),
                ),
                (
                    "changed_by_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of user/system",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "changed_by_identifier",
                    models.CharField(
                        blank=True,
                        help_text="Identifier of who made change",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When change was made"
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="Masters.scheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheme History",
                "verbose_name_plural": "Scheme History",
                "db_table": "scheme_history",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="SchemeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "include_all_items",
                    models.BooleanField(
                        default=False, help_text="Scheme applies to all items"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Category included in scheme",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Masters.category",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Item included in scheme",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Masters.item",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="Masters.scheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheme Item",
                "verbose_name_plural": "Scheme Items",
                "db_table": "scheme_item",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="scheme",
            index=models.Index(
                fields=["status", "effective_from", "effective_to"],
                name="scheme_status_ea9f59_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scheme",
            index=models.Index(
                fields=["company", "status"], name="scheme_company_b0a4c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheme",
            index=models.Index(
                fields=["scheme_type", "status"], name="scheme_scheme__312b60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schemehistory",
            index=models.Index(
                fields=["scheme", "-changed_at"], name="scheme_hist_scheme__58bc71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schemehistory",
            index=models.Index(
                fields=["action", "-changed_at"], name="scheme_hist_action_75b89a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="schemeitem",
            unique_together={("scheme", "item")},
        ),
    ]
