# Generated by Django 5.0.1 on 2026-02-12 12:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Masters", "0017_scheme_subtables_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="contact_person",
        ),
        migrations.RemoveField(
            model_name="location",
            name="contact_person_2",
        ),
        migrations.RemoveField(
            model_name="location",
            name="contact_person_3",
        ),
        migrations.RemoveField(
            model_name="location",
            name="email",
        ),
        migrations.RemoveField(
            model_name="location",
            name="email_2",
        ),
        migrations.RemoveField(
            model_name="location",
            name="email_3",
        ),
        migrations.RemoveField(
            model_name="location",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="location",
            name="phone_2",
        ),
        migrations.RemoveField(
            model_name="location",
            name="phone_3",
        ),
        migrations.AlterField(
            model_name="schemeapplicability",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="schemebenefit",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="schemecondition",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="schemehistory",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="schemeitem",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="LocationContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("erp_id", models.IntegerField(blank=True, default=None, null=True)),
                ("erp_code", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "created_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "created_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "modified_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("modified_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "is_deleted",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("contact_person", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="Masters.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location Contact",
                "verbose_name_plural": "Location Contacts",
                "db_table": "location_contacts",
                "ordering": ["-is_primary", "contact_person"],
            },
        ),
    ]
