# Generated by Django 5.0.1 on 2026-02-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Masters", "0019_channel_partner_contacts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="distributorcontact",
            name="updated_by_identifier",
        ),
        migrations.RemoveField(
            model_name="distributorcontact",
            name="updated_by_type",
        ),
        migrations.RemoveField(
            model_name="distributorcontact",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="retailercontact",
            name="updated_by_identifier",
        ),
        migrations.RemoveField(
            model_name="retailercontact",
            name="updated_by_type",
        ),
        migrations.RemoveField(
            model_name="retailercontact",
            name="updated_on",
        ),
        migrations.RemoveField(
            model_name="superstockistcontact",
            name="updated_by_identifier",
        ),
        migrations.RemoveField(
            model_name="superstockistcontact",
            name="updated_by_type",
        ),
        migrations.RemoveField(
            model_name="superstockistcontact",
            name="updated_on",
        ),
        migrations.AddField(
            model_name="distributorcontact",
            name="erp_code",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="distributorcontact",
            name="erp_id",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="distributorcontact",
            name="modified_by_identifier",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="distributorcontact",
            name="modified_by_type",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="distributorcontact",
            name="modified_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="retailercontact",
            name="erp_code",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="retailercontact",
            name="erp_id",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="retailercontact",
            name="modified_by_identifier",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="retailercontact",
            name="modified_by_type",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="retailercontact",
            name="modified_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="superstockistcontact",
            name="erp_code",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="superstockistcontact",
            name="erp_id",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="superstockistcontact",
            name="modified_by_identifier",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="superstockistcontact",
            name="modified_by_type",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="superstockistcontact",
            name="modified_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="distributorcontact",
            name="created_by_identifier",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="distributorcontact",
            name="created_by_type",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="distributorcontact",
            name="is_deleted",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="retailercontact",
            name="created_by_identifier",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="retailercontact",
            name="created_by_type",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="retailercontact",
            name="is_deleted",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="superstockistcontact",
            name="created_by_identifier",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="superstockistcontact",
            name="created_by_type",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="superstockistcontact",
            name="is_deleted",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
