# Generated by Django 5.0.1 on 2026-02-13 04:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Masters", "0020_remove_distributorcontact_updated_by_identifier_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="distributor",
            name="contact_person",
        ),
        migrations.RemoveField(
            model_name="distributor",
            name="contact_person_2",
        ),
        migrations.RemoveField(
            model_name="distributor",
            name="email",
        ),
        migrations.RemoveField(
            model_name="distributor",
            name="email_2",
        ),
        migrations.RemoveField(
            model_name="distributor",
            name="mobile",
        ),
        migrations.RemoveField(
            model_name="distributor",
            name="mobile_2",
        ),
        migrations.RemoveField(
            model_name="distributor",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="distributor",
            name="phone_2",
        ),
        migrations.RemoveField(
            model_name="retailer",
            name="contact_person",
        ),
        migrations.RemoveField(
            model_name="retailer",
            name="contact_person_2",
        ),
        migrations.RemoveField(
            model_name="retailer",
            name="email",
        ),
        migrations.RemoveField(
            model_name="retailer",
            name="email_2",
        ),
        migrations.RemoveField(
            model_name="retailer",
            name="mobile",
        ),
        migrations.RemoveField(
            model_name="retailer",
            name="mobile_2",
        ),
        migrations.RemoveField(
            model_name="retailer",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="retailer",
            name="phone_2",
        ),
        migrations.RemoveField(
            model_name="superstockist",
            name="contact_person",
        ),
        migrations.RemoveField(
            model_name="superstockist",
            name="contact_person_2",
        ),
        migrations.RemoveField(
            model_name="superstockist",
            name="email",
        ),
        migrations.RemoveField(
            model_name="superstockist",
            name="email_2",
        ),
        migrations.RemoveField(
            model_name="superstockist",
            name="mobile",
        ),
        migrations.RemoveField(
            model_name="superstockist",
            name="mobile_2",
        ),
        migrations.RemoveField(
            model_name="superstockist",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="superstockist",
            name="phone_2",
        ),
    ]
