# Generated by Django 5.0.1 on 2026-02-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Masters", "0021_remove_distributor_contact_person_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricebookdocument",
            name="selected_brands",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of selected brand IDs for filtering items",
            ),
        ),
        migrations.AddField(
            model_name="pricebookdocument",
            name="selected_categories",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of selected category IDs for filtering items",
            ),
        ),
        migrations.AlterField(
            model_name="channelpartnerconfiguration",
            name="enforce_channel_hierarchy",
            field=models.BooleanField(
                default=False,
                help_text="Enforce Superstockist -> Distributor -> Retailer hierarchy",
            ),
        ),
        migrations.DeleteModel(
            name="ChannelPartnerAttachment",
        ),
    ]
