# Generated by Django 5.0.1 on 2026-02-16 11:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Masters", "0022_pricebookdocument_selected_brands_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelPartnerAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("erp_id", models.IntegerField(blank=True, default=None, null=True)),
                ("erp_code", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "created_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "created_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "modified_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("modified_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "is_deleted",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("object_id", models.CharField(max_length=255)),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("AADHAR", "Aadhar"),
                            ("PAN", "PAN"),
                            ("AGREEMENT", "Agreement"),
                            ("SHOP_PICTURE", "Shop Picture"),
                            ("CANCELLED_CHEQUE", "Cancelled Cheque"),
                            ("OWNER_PICTURE", "Representative/Shop Owner Picture"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Type of attachment",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Attachment file",
                        upload_to="channel_partners/attachments/%Y/%m/",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True,
                        help_text="Original filename",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Description for other attachments",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Channel Partner Attachment",
                "verbose_name_plural": "Channel Partner Attachments",
                "db_table": "channel_partner_attachments",
                "ordering": ["-created_on"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="channel_par_content_2e8183_idx",
                    ),
                    models.Index(
                        fields=["attachment_type"],
                        name="channel_par_attachm_659dc3_idx",
                    ),
                ],
            },
        ),
    ]
