# Generated by Codex on 2026-02-23

from django.db import migrations


def suffix_deleted_category_names(apps, schema_editor):
    Category = apps.get_model("Masters", "Category")

    for category in Category.objects.filter(is_deleted=True):
        name = (category.name or "").strip()
        if not name or "_DEL_" in name:
            continue

        suffix = f"_DEL_{str(category.id)[:8]}"
        max_name_length = Category._meta.get_field("name").max_length
        allowed_base_length = max_name_length - len(suffix)
        if allowed_base_length < 1:
            allowed_base_length = 1

        category.name = f"{name[:allowed_base_length]}{suffix}"
        category.save(update_fields=["name"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("Masters", "0023_channelpartnerattachment"),
    ]

    operations = [
        migrations.RunPython(suffix_deleted_category_names, noop_reverse),
    ]
