# Generated by Codex on 2026-02-23

from django.db import migrations


def _suffix_name(instance, field_name="name"):
    current_value = (getattr(instance, field_name, "") or "").strip()
    if not current_value or "_DEL_" in current_value:
        return None

    suffix = f"_DEL_{str(instance.id)[:8]}"
    field = instance._meta.get_field(field_name)
    max_length = getattr(field, "max_length", None)

    if not max_length:
        return f"{current_value}{suffix}"

    allowed_base_length = max_length - len(suffix)
    if allowed_base_length < 1:
        allowed_base_length = 1

    return f"{current_value[:allowed_base_length]}{suffix}"


def fix_soft_deleted_master_uniqueness(apps, schema_editor):
    # Name-unique or name-based unique constraints
    for model_name in ["UOM", "Category", "Brand", "Tax", "OutletType", "Area"]:
        model = apps.get_model("Masters", model_name)
        for obj in model.objects.filter(is_deleted=True):
            new_name = _suffix_name(obj, "name")
            if new_name:
                obj.name = new_name
                obj.save(update_fields=["name"])

    # Free nullable unique identifiers to allow reuse after soft delete
    company_model = apps.get_model("Masters", "Company")
    company_model.objects.filter(is_deleted=True).exclude(pan_number__isnull=True).update(pan_number=None)
    company_model.objects.filter(is_deleted=True).exclude(gst_number__isnull=True).update(gst_number=None)

    item_model = apps.get_model("Masters", "Item")
    item_model.objects.filter(is_deleted=True).exclude(barcode__isnull=True).update(barcode=None)

    for model_name in ["Superstockist", "Distributor", "Retailer"]:
        model = apps.get_model("Masters", model_name)
        model.objects.filter(is_deleted=True).exclude(gstin__isnull=True).update(gstin=None)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("Masters", "0024_fix_deleted_category_names"),
    ]

    operations = [
        migrations.RunPython(fix_soft_deleted_master_uniqueness, noop_reverse),
    ]
