# Generated by Codex on 2026-02-23

from django.db import migrations


def set_item_code_not_required(apps, schema_editor):
    ItemFieldConfiguration = apps.get_model("Masters", "ItemFieldConfiguration")
    ItemFieldConfiguration.objects.filter(field_name="code").update(is_required=False)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("Masters", "0025_fix_soft_delete_uniqueness_for_masters"),
    ]

    operations = [
        migrations.RunPython(set_item_code_not_required, noop_reverse),
    ]
