# Generated by Django 5.0.1 on 2026-02-24 12:58

import Masters.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Masters", "0027_location_companies_m2m"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("erp_id", models.IntegerField(blank=True, default=None, null=True)),
                ("erp_code", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "created_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "created_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "modified_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("modified_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "is_deleted",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Route",
                "verbose_name_plural": "Routes",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="Masters_rou_name_6e9f05_idx"),
                    models.Index(
                        fields=["is_active"], name="Masters_rou_is_acti_37bac4_idx"
                    ),
                ],
            },
            bases=(Masters.validators.DuplicateValidationMixin, models.Model),
        ),
        migrations.CreateModel(
            name="RouteCoverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="route_coverages",
                        to="Masters.area",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="route_coverages",
                        to="Masters.city",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverages",
                        to="Masters.route",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="route_coverages",
                        to="Masters.state",
                    ),
                ),
            ],
            options={
                "db_table": "route_coverages",
                "indexes": [
                    models.Index(
                        fields=["route", "state", "city"],
                        name="route_cover_route_i_885658_idx",
                    ),
                    models.Index(
                        fields=["state", "city", "area"],
                        name="route_cover_state_i_e63def_idx",
                    ),
                ],
                "unique_together": {("route", "state", "city", "area")},
            },
        ),
    ]
