# Generated by Django 4.2.6 on 2026-03-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0028_route_routecoverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='company_logos'),
        ),
    ]
