# Generated by Django 4.2.6 on 2026-03-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0029_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='items/images/'),
        ),
    ]
