# Generated by Django 4.2.6 on 2026-03-17 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0030_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this scheme belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='Masters.company'),
        ),
    ]
