# Generated by Django 5.2.5 on 2026-03-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0031_alter_scheme_company'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='user_companies',
            field=models.ManyToManyField(blank=True, help_text='Companies for user access', related_name='distributor_user_companies', to='Masters.company'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='user_device_access',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Only Mobile'), (2, 'Only Web'), (3, 'Both'), (4, 'None')], default=3, help_text='Device access for user', null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='user_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups for user', related_name='distributor_user_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='user_has_all_companies',
            field=models.BooleanField(default=False, help_text='User has access to all companies'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='user_has_all_locations',
            field=models.BooleanField(default=False, help_text='User has access to all locations'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='user_locations',
            field=models.ManyToManyField(blank=True, help_text='Locations for user access', related_name='distributor_user_locations', to='Masters.location'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='user_password',
            field=models.CharField(blank=True, help_text='Password for auto-created user', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='user_username',
            field=models.CharField(blank=True, help_text='Username for auto-created user', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='user_companies',
            field=models.ManyToManyField(blank=True, help_text='Companies for user access', related_name='retailer_user_companies', to='Masters.company'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='user_device_access',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Only Mobile'), (2, 'Only Web'), (3, 'Both'), (4, 'None')], default=3, help_text='Device access for user', null=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='user_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups for user', related_name='retailer_user_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='user_has_all_companies',
            field=models.BooleanField(default=False, help_text='User has access to all companies'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='user_has_all_locations',
            field=models.BooleanField(default=False, help_text='User has access to all locations'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='user_locations',
            field=models.ManyToManyField(blank=True, help_text='Locations for user access', related_name='retailer_user_locations', to='Masters.location'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='user_password',
            field=models.CharField(blank=True, help_text='Password for auto-created user', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='user_username',
            field=models.CharField(blank=True, help_text='Username for auto-created user', max_length=255, null=True),
        ),
    ]
