# Generated by Django 5.2.5 on 2026-03-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0032_add_user_fields_to_distributor_retailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='user_phone',
            field=models.CharField(blank=True, help_text='Phone number for auto-created user', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='user_phone',
            field=models.CharField(blank=True, help_text='Phone number for auto-created user', max_length=15, null=True),
        ),
    ]
