# Generated by Django 4.2.6 on 2026-03-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0033_add_user_phone_to_distributor_retailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemebenefit',
            name='benefit_type',
            field=models.CharField(choices=[('DISCOUNT_PERCENTAGE', 'Discount %'), ('DISCOUNT_AMOUNT', 'Discount Amount'), ('FREE_ITEM', 'Free Product'), ('FREE_QUANTITY', 'Free Quantity'), ('CASHBACK', 'Cashback')], help_text='Type of benefit', max_length=30),
        ),
    ]
