# Generated by Django 5.2.5 on 2026-04-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0034_alter_schemebenefit_benefit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemecondition',
            name='combo_items',
            field=models.JSONField(blank=True, default=list, help_text='List of item IDs required for ITEM_COMBO condition'),
        ),
    ]
