# Generated by Django 4.2.6 on 2026-04-06 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0035_add_combo_items_to_schemecondition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemecondition',
            old_name='combo_items',
            new_name='items',
        ),
    ]
