# Generated by Django 4.2.6 on 2026-04-08 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0036_rename_combo_items_schemecondition_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheme',
            options={'ordering': ['-priority', '-created_on'], 'permissions': (('can_cancel_scheme', 'Can cancel scheme'),), 'verbose_name': 'Scheme', 'verbose_name_plural': 'Schemes'},
        ),
    ]
