# Generated by Django 4.2.6 on 2026-04-21 13:48

import Masters.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0037_alter_scheme_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_id', models.IntegerField(blank=True, default=None, null=True)),
                ('erp_code', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('modified_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='districts', to='Masters.state')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['name'],
                'unique_together': {('name', 'state')},
            },
            bases=(Masters.validators.DuplicateValidationMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['name'], 'verbose_name': 'Village/Town', 'verbose_name_plural': 'Villages/Towns'},
        ),
        migrations.AddField(
            model_name='area',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='areas', to='Masters.country'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Billing country', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='distributors', to='Masters.country'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='shipping_country',
            field=models.ForeignKey(blank=True, help_text='Shipping country', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='distributors_shipping', to='Masters.country'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='shipping_street',
            field=models.CharField(blank=True, help_text='Shipping street', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='street',
            field=models.CharField(blank=True, help_text='Billing street', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cities', to='Masters.country'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='area',
            field=models.ForeignKey(blank=True, help_text='Billing village/town', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='distributors', to='Masters.area'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='shipping_area',
            field=models.ForeignKey(blank=True, help_text='Shipping village/town', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='distributors_shipping', to='Masters.area'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'state')},
        ),
        migrations.CreateModel(
            name='Mandal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_id', models.IntegerField(blank=True, default=None, null=True)),
                ('erp_code', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('modified_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mandals', to='Masters.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mandals', to='Masters.state')),
            ],
            options={
                'verbose_name': 'Mandal',
                'verbose_name_plural': 'Mandals',
                'ordering': ['name'],
                'unique_together': {('name', 'district')},
            },
            bases=(Masters.validators.DuplicateValidationMixin, models.Model),
        ),
        migrations.AddField(
            model_name='area',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='areas', to='Masters.district'),
        ),
        migrations.AddField(
            model_name='area',
            name='mandal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='areas', to='Masters.mandal'),
        ),
        migrations.AddField(
            model_name='city',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cities', to='Masters.district'),
        ),
        migrations.AddField(
            model_name='city',
            name='mandal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cities', to='Masters.mandal'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='district',
            field=models.ForeignKey(blank=True, help_text='Billing district', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='distributors', to='Masters.district'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='mandal',
            field=models.ForeignKey(blank=True, help_text='Billing mandal', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='distributors', to='Masters.mandal'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='shipping_district',
            field=models.ForeignKey(blank=True, help_text='Shipping district', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='distributors_shipping', to='Masters.district'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='shipping_mandal',
            field=models.ForeignKey(blank=True, help_text='Shipping mandal', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='distributors_shipping', to='Masters.mandal'),
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_id', models.IntegerField(blank=True, default=None, null=True)),
                ('erp_code', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('modified_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('pincode', models.CharField(blank=True, help_text='PIN Code', max_length=10, null=True)),
                ('landmark', models.CharField(blank=True, help_text='Nearby landmark', max_length=200, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='streets', to='Masters.area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='streets', to='Masters.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='streets', to='Masters.state')),
            ],
            options={
                'verbose_name': 'Street',
                'verbose_name_plural': 'Streets',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['area', 'city'], name='Masters_str_area_id_19c08b_idx'), models.Index(fields=['pincode'], name='Masters_str_pincode_401454_idx')],
                'unique_together': {('name', 'area')},
            },
            bases=(Masters.validators.DuplicateValidationMixin, models.Model),
        ),
    ]
