# Generated by Django 4.2.11 on 2026-06-02 06:43

import Masters.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0039_remove_street_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_id', models.IntegerField(blank=True, default=None, null=True)),
                ('erp_code', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('modified_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(help_text='Agent/Broker name', max_length=200)),
                ('phone', models.CharField(help_text='Phone number', max_length=15)),
                ('email', models.EmailField(blank=True, help_text='Email address (optional)', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'db_table': 'agents',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='agents_code_01dbf9_idx'), models.Index(fields=['name'], name='agents_name_6f5710_idx'), models.Index(fields=['is_active'], name='agents_is_acti_3fbec7_idx')],
            },
            bases=(Masters.validators.DuplicateValidationMixin, models.Model),
        ),
        migrations.AddField(
            model_name='distributor',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Tagged agent/broker', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributors', to='Masters.agent'),
        ),
    ]
