# Generated by Django 5.2.14 on 2026-06-17 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0040_agent_distributor_agent'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='distributorlocation',
            name='distributor_state_i_8e90fa_idx',
        ),
        migrations.AlterUniqueTogether(
            name='distributorlocation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='distributorlocation',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='distributor_locations', to='Masters.district'),
        ),
        migrations.AddField(
            model_name='distributorlocation',
            name='mandal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='distributor_locations', to='Masters.mandal'),
        ),
        migrations.AlterUniqueTogether(
            name='distributorlocation',
            unique_together={('distributor', 'state', 'district', 'mandal', 'city', 'area')},
        ),
        migrations.AddIndex(
            model_name='distributorlocation',
            index=models.Index(fields=['state', 'district', 'mandal', 'city', 'area'], name='distributor_state_i_6a23c3_idx'),
        ),
    ]
