# Generated by Django 4.2.11 on 2026-06-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0041_remove_distributorlocation_distributor_state_i_8e90fa_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributorcontact',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
