# Generated by Django 5.2.16 on 2026-07-11 14:26

import Masters.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0042_alter_distributorcontact_contact_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_id', models.IntegerField(blank=True, default=None, null=True)),
                ('erp_code', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('modified_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('authorized_level', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('authorized_by_type', models.CharField(blank=True, max_length=30, null=True)),
                ('authorized_by_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('authorized_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('current_authorized_level', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('current_authorized_status', models.SmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1, null=True)),
                ('current_authorized_by_type', models.CharField(blank=True, max_length=30, null=True)),
                ('current_authorized_by_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('current_authorized_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('authorized_status', models.SmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1, null=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('developer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('project_type', models.CharField(choices=[('PLOT', 'Plot'), ('FLAT', 'Flat'), ('VILLA', 'Villa'), ('MIXED', 'Mixed')], db_index=True, default='PLOT', max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('approval_type', models.CharField(choices=[('GVMC', 'GVMC'), ('VMRDA', 'VMRDA'), ('DTCP', 'DTCP'), ('HMDA', 'HMDA'), ('PANCHAYAT', 'Panchayat'), ('PENDING', 'Pending'), ('NA', 'N/A')], default='PENDING', max_length=20)),
                ('rera_number', models.CharField(blank=True, max_length=100, null=True)),
                ('total_area', models.CharField(blank=True, help_text='e.g. "5 acres"', max_length=100, null=True)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('possession_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, help_text='Primary project image', max_length=500, null=True)),
                ('brochure_url', models.URLField(blank=True, max_length=500, null=True)),
                ('layout_plan_url', models.URLField(blank=True, max_length=500, null=True)),
                ('floor_plan_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('SOLD_OUT', 'Sold Out')], db_index=True, default='UPCOMING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='projects', to='Masters.location')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['name'],
                'permissions': [('export_project', 'Can export projects')],
            },
            bases=(Masters.validators.DuplicateValidationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_id', models.IntegerField(blank=True, default=None, null=True)),
                ('erp_code', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('modified_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('from_status', models.CharField(blank=True, choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('SOLD_OUT', 'Sold Out')], max_length=20, null=True)),
                ('to_status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('SOLD_OUT', 'Sold Out')], max_length=20)),
                ('changed_by_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='Masters.project')),
            ],
            options={
                'verbose_name': 'Project Status History',
                'verbose_name_plural': 'Project Status History',
                'ordering': ['-created_on'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='Masters_pro_status_244fde_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_type'], name='Masters_pro_project_ccda9c_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_active'], name='Masters_pro_is_acti_69051d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectstatushistory',
            index=models.Index(fields=['project', '-created_on'], name='Masters_pro_project_246b7c_idx'),
        ),
    ]
