# Generated by Django 5.2.16 on 2026-07-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0043_project_projectstatushistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='address',
        ),
        migrations.RemoveField(
            model_name='project',
            name='brochure_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='floor_plan_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='launch_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='layout_plan_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='possession_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='rera_number',
        ),
        migrations.RemoveField(
            model_name='project',
            name='total_area',
        ),
        migrations.AddField(
            model_name='project',
            name='sub',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
