# Generated by Django 5.2.16 on 2026-07-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0044_remove_project_address_remove_project_brochure_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, help_text='Project location (free text)', max_length=255, null=True),
        ),
    ]
