# Generated by Django 5.2.16 on 2026-07-27 13:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0045_change_project_location_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='amenities',
            field=models.TextField(blank=True, help_text='List of amenities (can be JSON or comma-separated)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='brochure',
            field=models.FileField(blank=True, help_text='Project brochure PDF', null=True, upload_to='projects/brochures/'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed project description', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='elevation_image',
            field=models.ImageField(blank=True, help_text='Main elevation image for project preview', null=True, upload_to='projects/elevation/'),
        ),
        migrations.AddField(
            model_name='project',
            name='floor_plans',
            field=models.JSONField(blank=True, default=list, help_text='List of floor plan image URLs'),
        ),
        migrations.AddField(
            model_name='project',
            name='floor_plans_text',
            field=models.TextField(blank=True, help_text='Floor plan details as text description', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery',
            field=models.JSONField(blank=True, default=list, help_text='List of gallery image URLs'),
        ),
        migrations.AddField(
            model_name='project',
            name='overview',
            field=models.TextField(blank=True, help_text='Brief project overview (shown in cards/previews)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='specifications',
            field=models.TextField(blank=True, help_text='Project specifications (can be JSON or structured text)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail image for cards/lists', null=True, upload_to='projects/thumbnails/'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_id', models.IntegerField(blank=True, default=None, null=True)),
                ('erp_code', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('modified_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(upload_to='projects/images/')),
                ('image_type', models.CharField(choices=[('GALLERY', 'Gallery'), ('FLOOR_PLAN', 'Floor Plan'), ('ELEVATION', 'Elevation')], default='GALLERY', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Masters.project')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
                'ordering': ['order', 'created_on'],
            },
        ),
    ]
