# Generated by Django 5.2.16 on 2026-07-30 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0046_project_amenities_project_brochure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.DeleteModel(
            name='ProjectStatusHistory',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
