# Generated by Django 5.0.1 on 2026-02-17 10:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Masters", "0023_channelpartnerattachment"),
        ("Receipts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerCredit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("erp_id", models.IntegerField(blank=True, default=None, null=True)),
                ("erp_code", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "created_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "created_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "modified_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("modified_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "is_deleted",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "authorized_level",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "authorized_by_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "authorized_by_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("authorized_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "current_authorized_level",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "current_authorized_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")],
                        default=1,
                        null=True,
                    ),
                ),
                (
                    "current_authorized_by_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "current_authorized_by_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_authorized_on",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "authorized_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")],
                        default=1,
                        null=True,
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("RETAILER", "Retailer"),
                            ("DISTRIBUTOR", "Distributor"),
                            ("SUPERSTOCKIST", "Superstockist"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("credit_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "available_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_credits",
                        to="Masters.company",
                    ),
                ),
                (
                    "distributor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credits",
                        to="Masters.distributor",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_credits",
                        to="Masters.location",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credits",
                        to="Receipts.receipt",
                    ),
                ),
                (
                    "retailer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credits",
                        to="Masters.retailer",
                    ),
                ),
                (
                    "superstockist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credits",
                        to="Masters.superstockist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Credit",
                "verbose_name_plural": "Customer Credits",
                "db_table": "customer_credit",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="CreditUtilization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "utilized_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("utilized_on", models.DateTimeField(auto_now_add=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_utilizations",
                        to="Receipts.receipt",
                    ),
                ),
                (
                    "credit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="utilizations",
                        to="Receipts.customercredit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Utilization",
                "verbose_name_plural": "Credit Utilizations",
                "db_table": "credit_utilization",
                "ordering": ["-utilized_on"],
            },
        ),
        migrations.AddIndex(
            model_name="customercredit",
            index=models.Index(
                fields=["customer_type"], name="customer_cr_custome_bb9f24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customercredit",
            index=models.Index(
                fields=["company", "location"], name="customer_cr_company_ed3b42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customercredit",
            index=models.Index(
                fields=["-created_on"], name="customer_cr_created_45077b_idx"
            ),
        ),
    ]
