# Generated by Django 5.0.1 on 2026-02-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Receipts", "0002_customercredit_creditutilization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="payment_mode",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("CHEQUE", "Cheque"),
                    ("NEFT", "NEFT"),
                    ("RTGS", "RTGS"),
                    ("UPI", "UPI"),
                    ("CARD", "Card"),
                    ("CREDIT", "Credit"),
                ],
                max_length=20,
            ),
        ),
    ]
