# Generated by Django 5.0.1 on 2026-02-18 11:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Masters", "0023_channelpartnerattachment"),
        ("Receipts", "0003_alter_receipt_payment_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerLedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("erp_id", models.IntegerField(blank=True, default=None, null=True)),
                ("erp_code", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "created_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "created_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "modified_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("modified_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "is_deleted",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "authorized_level",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "authorized_by_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "authorized_by_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("authorized_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "current_authorized_level",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "current_authorized_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")],
                        default=1,
                        null=True,
                    ),
                ),
                (
                    "current_authorized_by_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "current_authorized_by_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_authorized_on",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "authorized_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")],
                        default=1,
                        null=True,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[("INVOICE", "Invoice"), ("RECEIPT", "Receipt")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("document_id", models.UUIDField(db_index=True)),
                ("document_number", models.CharField(db_index=True, max_length=50)),
                ("document_date", models.DateField(db_index=True)),
                ("posting_date", models.DateField(db_index=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("INVOICE_POSTED", "Invoice Posted"),
                            ("RECEIPT_POSTED", "Receipt Posted"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("RETAILER", "Retailer"),
                            ("DISTRIBUTOR", "Distributor"),
                            ("SUPERSTOCKIST", "Superstockist"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "debit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "credit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "entry_status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        db_index=True,
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("meta_data", models.JSONField(blank=True, default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_ledger_entries",
                        to="Masters.company",
                    ),
                ),
                (
                    "distributor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="Masters.distributor",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_ledger_entries",
                        to="Masters.location",
                    ),
                ),
                (
                    "retailer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="Masters.retailer",
                    ),
                ),
                (
                    "superstockist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="Masters.superstockist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Ledger Entry",
                "verbose_name_plural": "Customer Ledger Entries",
                "db_table": "customer_ledger_entry",
                "ordering": ["posting_date", "created_on"],
                "indexes": [
                    models.Index(
                        fields=["document_type", "document_id"],
                        name="customer_le_documen_3385d7_idx",
                    ),
                    models.Index(
                        fields=["customer_type", "posting_date"],
                        name="customer_le_custome_719d61_idx",
                    ),
                    models.Index(
                        fields=["company", "location", "posting_date"],
                        name="customer_le_company_3894a7_idx",
                    ),
                    models.Index(
                        fields=["entry_status", "-created_on"],
                        name="customer_le_entry_s_f57e42_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="customerledgerentry",
            constraint=models.UniqueConstraint(
                fields=("document_type", "document_id", "event_type"),
                name="customer_ledger_unique_document_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="customerledgerentry",
            constraint=models.CheckConstraint(
                check=models.Q(("debit_amount__gte", 0), ("credit_amount__gte", 0)),
                name="customer_ledger_non_negative_amounts",
            ),
        ),
        migrations.AddConstraint(
            model_name="customerledgerentry",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("debit_amount__gt", 0), ("credit_amount", 0)),
                    models.Q(("credit_amount__gt", 0), ("debit_amount", 0)),
                    _connector="OR",
                ),
                name="customer_ledger_single_sided_entry",
            ),
        ),
    ]
