# Generated by Django 4.2.6 on 2026-03-27 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0034_alter_schemebenefit_benefit_type'),
        ('Receipts', '0004_customerledgerentry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerledgerentry',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_ledger_entries', to='Masters.location'),
        ),
    ]
