# Generated by Django 4.2.6 on 2026-01-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("System", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertconfig",
            name="authorized_status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")],
                default=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="alertconfig",
            name="current_authorized_status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")],
                default=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="alertconfigusers",
            name="authorized_status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")],
                default=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="alertconfigusers",
            name="current_authorized_status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")],
                default=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="announcements",
            name="authorized_status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")],
                default=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="announcements",
            name="current_authorized_status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")],
                default=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="taskscheduler",
            name="authorized_status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")],
                default=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="taskscheduler",
            name="current_authorized_status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")],
                default=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="authorized_status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")],
                default=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="current_authorized_status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")],
                default=1,
                null=True,
            ),
        ),
    ]
