# Generated by Django 5.0.1 on 2026-02-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("System", "0002_alter_alertconfig_authorized_status_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertconfig",
            name="send_to_groups",
            field=models.ManyToManyField(
                blank=True, related_name="alertconfigs", to="auth.group"
            ),
        ),
    ]
