# Generated by Django 4.2.6 on 2026-03-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0003_alter_alertconfig_send_to_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterpreset',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='savedfilter',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
