# Generated by Django 5.2.16 on 2026-07-20 12:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0004_filterpreset_code_savedfilter_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_id', models.IntegerField(blank=True, default=None, null=True)),
                ('erp_code', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('modified_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.CharField(help_text='Configuration name (e.g. "Gmail", "SendGrid")', max_length=100)),
                ('host', models.CharField(help_text='SMTP server host (e.g. smtp.gmail.com)', max_length=255)),
                ('port', models.PositiveIntegerField(default=587, help_text='SMTP port (587 for TLS, 465 for SSL)')),
                ('username', models.CharField(help_text='SMTP username / email', max_length=255)),
                ('password', models.CharField(help_text='SMTP password / app password', max_length=255)),
                ('use_tls', models.BooleanField(default=True, help_text='Use TLS encryption')),
                ('use_ssl', models.BooleanField(default=False, help_text='Use SSL encryption')),
                ('from_email', models.EmailField(help_text='Default "From" email address', max_length=254)),
                ('from_name', models.CharField(blank=True, help_text='Display name for sender', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Active configuration (only one should be active)')),
            ],
            options={
                'verbose_name': 'SMTP Configuration',
                'verbose_name_plural': 'SMTP Configurations',
                'ordering': ['-is_active', '-created_on'],
            },
        ),
    ]
