# Generated by Django 4.2.6 on 2026-01-23 04:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Masters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatchItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("erp_id", models.IntegerField(blank=True, default=None, null=True)),
                ("erp_code", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "created_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "created_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "modified_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("modified_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "is_deleted",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "authorized_level",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "authorized_by_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "authorized_by_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("authorized_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "current_authorized_level",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "current_authorized_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Pending"),
                            (2, "Approved"),
                            (3, "Rejected"),
                            (4, "Skipped"),
                        ],
                        default=1,
                        null=True,
                    ),
                ),
                (
                    "current_authorized_by_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "current_authorized_by_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_authorized_on",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "authorized_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Pending"),
                            (2, "Approved"),
                            (3, "Rejected"),
                            (4, "Skipped"),
                        ],
                        default=4,
                        null=True,
                    ),
                ),
                (
                    "quantity_ordered",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Total quantity in sales order",
                        max_digits=10,
                    ),
                ),
                (
                    "quantity_dispatched",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Quantity being dispatched in this plan",
                        max_digits=10,
                    ),
                ),
                ("delivery_sequence", models.IntegerField(default=1)),
                ("loading_sequence", models.IntegerField(default=1)),
                (
                    "unloading_sequence",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("LOADED", "Loaded"),
                            ("IN_TRANSIT", "In Transit"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed Delivery"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_delivery_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("actual_delivery_time", models.DateTimeField(blank=True, null=True)),
                ("delivery_notes", models.TextField(blank=True)),
                ("delivered_by", models.CharField(blank=True, max_length=100)),
                ("received_by", models.CharField(blank=True, max_length=100)),
                (
                    "delivery_proof",
                    models.FileField(
                        blank=True, null=True, upload_to="dispatch/delivery_proof/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispatch Item",
                "verbose_name_plural": "Dispatch Items",
                "db_table": "dispatch_item",
                "ordering": ["delivery_sequence", "loading_sequence"],
            },
        ),
        migrations.CreateModel(
            name="DispatchPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("erp_id", models.IntegerField(blank=True, default=None, null=True)),
                ("erp_code", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "created_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "created_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "modified_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("modified_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "is_deleted",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "authorized_level",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "authorized_by_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "authorized_by_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("authorized_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "current_authorized_level",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "current_authorized_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Pending"),
                            (2, "Approved"),
                            (3, "Rejected"),
                            (4, "Skipped"),
                        ],
                        default=1,
                        null=True,
                    ),
                ),
                (
                    "current_authorized_by_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "current_authorized_by_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_authorized_on",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "authorized_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Pending"),
                            (2, "Approved"),
                            (3, "Rejected"),
                            (4, "Skipped"),
                        ],
                        default=4,
                        null=True,
                    ),
                ),
                (
                    "dispatch_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("dispatch_date", models.DateField(db_index=True)),
                ("planned_dispatch_date", models.DateField()),
                (
                    "vehicle_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "vehicle_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("vehicle_capacity", models.CharField(blank=True, max_length=50)),
                ("driver_name", models.CharField(blank=True, max_length=100)),
                ("driver_phone", models.CharField(blank=True, max_length=20)),
                ("driver_license", models.CharField(blank=True, max_length=50)),
                ("route_name", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("CONFIRMED", "Confirmed"),
                            ("IN_TRANSIT", "In Transit"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("total_orders", models.IntegerField(default=0)),
                (
                    "total_weight",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_volume",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("estimated_start_time", models.DateTimeField(blank=True, null=True)),
                ("estimated_end_time", models.DateTimeField(blank=True, null=True)),
                ("actual_start_time", models.DateTimeField(blank=True, null=True)),
                ("actual_end_time", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispatch_plans",
                        to="Masters.company",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispatch_plans",
                        to="Masters.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispatch Plan",
                "verbose_name_plural": "Dispatch Plans",
                "db_table": "dispatch_plan",
                "ordering": ["-dispatch_date", "-created_on"],
            },
        ),
        migrations.CreateModel(
            name="DispatchOrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("erp_id", models.IntegerField(blank=True, default=None, null=True)),
                ("erp_code", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "created_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "created_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "modified_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("modified_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "is_deleted",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "authorized_level",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "authorized_by_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "authorized_by_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("authorized_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "current_authorized_level",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "current_authorized_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Pending"),
                            (2, "Approved"),
                            (3, "Rejected"),
                            (4, "Skipped"),
                        ],
                        default=1,
                        null=True,
                    ),
                ),
                (
                    "current_authorized_by_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "current_authorized_by_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_authorized_on",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "authorized_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Pending"),
                            (2, "Approved"),
                            (3, "Rejected"),
                            (4, "Skipped"),
                        ],
                        default=4,
                        null=True,
                    ),
                ),
                (
                    "quantity_ordered",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Quantity of this item in sales order",
                        max_digits=10,
                    ),
                ),
                (
                    "quantity_dispatched",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Quantity of this item being dispatched",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("LOADED", "Loaded"),
                            ("IN_TRANSIT", "In Transit"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed Delivery"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "dispatch_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="Dispatch.dispatchitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispatch Order Item",
                "verbose_name_plural": "Dispatch Order Items",
                "db_table": "dispatch_order_item",
                "ordering": ["sales_order_item__item__name"],
            },
        ),
    ]
