# Generated by Django 4.2.6 on 2026-01-23 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Sales", "0001_initial"),
        ("Dispatch", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatchorderitem",
            name="sales_order_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="dispatch_order_items",
                to="Sales.salesorderitem",
            ),
        ),
        migrations.AddField(
            model_name="dispatchitem",
            name="dispatch_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="Dispatch.dispatchplan",
            ),
        ),
        migrations.AddField(
            model_name="dispatchitem",
            name="sales_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="dispatch_items",
                to="Sales.salesorder",
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchplan",
            index=models.Index(
                fields=["dispatch_number"], name="dispatch_pl_dispatc_4e707a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchplan",
            index=models.Index(
                fields=["dispatch_date", "status"],
                name="dispatch_pl_dispatc_9bdd0e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchplan",
            index=models.Index(
                fields=["company", "status"], name="dispatch_pl_company_6506fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchplan",
            index=models.Index(
                fields=["-created_on"], name="dispatch_pl_created_fe7758_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchorderitem",
            index=models.Index(
                fields=["dispatch_item", "sales_order_item"],
                name="dispatch_or_dispatc_6de068_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchorderitem",
            index=models.Index(fields=["status"], name="dispatch_or_status_b69904_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="dispatchorderitem",
            unique_together={("dispatch_item", "sales_order_item")},
        ),
        migrations.AddIndex(
            model_name="dispatchitem",
            index=models.Index(
                fields=["dispatch_plan", "sales_order"],
                name="dispatch_it_dispatc_1196bb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchitem",
            index=models.Index(fields=["status"], name="dispatch_it_status_a781ba_idx"),
        ),
        migrations.AddIndex(
            model_name="dispatchitem",
            index=models.Index(
                fields=["delivery_sequence"], name="dispatch_it_deliver_6b3380_idx"
            ),
        ),
    ]
