# Generated by Django 5.0.1 on 2026-02-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Dispatch", "0003_alter_dispatchitem_authorized_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatchplan",
            name="lr_no",
            field=models.CharField(
                blank=True, help_text="Lorry Receipt Number", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="dispatchplan",
            name="stock_insurance",
            field=models.BooleanField(
                default=False, help_text="Whether stock is insured"
            ),
        ),
        migrations.AlterField(
            model_name="dispatchplan",
            name="vehicle_capacity",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
