# Generated by Django 5.0.1 on 2026-02-04 13:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Dispatch", "0004_dispatchplan_lr_no_dispatchplan_stock_insurance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatchPlanAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("erp_id", models.IntegerField(blank=True, default=None, null=True)),
                ("erp_code", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "created_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "created_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "modified_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("modified_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "is_deleted",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("VEHICLE_RC", "Vehicle RC"),
                            ("VEHICLE_INSURANCE", "Vehicle Insurance"),
                            ("VEHICLE_PERMIT", "Vehicle Permit"),
                            ("VEHICLE_POLLUTION", "Vehicle Pollution Certificate"),
                            ("DRIVER_LICENSE", "Driver License"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="dispatch_plans/attachments/%Y/%m/"),
                ),
                (
                    "original_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dispatch_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="Dispatch.dispatchplan",
                    ),
                ),
            ],
            options={
                "db_table": "dispatch_plan_attachments",
                "ordering": ["-created_on"],
            },
        ),
    ]
