# Generated by Django 5.0.1 on 2026-02-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Dispatch", "0005_dispatchplanattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispatchitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("LOADED", "Loaded"),
                    ("DELIVERED", "Delivered"),
                    ("FAILED", "Failed Delivery"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dispatchorderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("LOADED", "Loaded"),
                    ("DELIVERED", "Delivered"),
                    ("FAILED", "Failed Delivery"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dispatchplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("CONFIRMED", "Confirmed"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
