# Generated by Django 5.0.1 on 2026-02-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Dispatch", "0006_alter_dispatchitem_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispatchplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
