# Generated by Django 4.2.6 on 2026-02-24 07:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Dispatch", "0008_dispatch_company_to_subtables"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="dispatchplan",
            name="dispatch_pl_company_6506fc_idx",
        ),
        migrations.RenameIndex(
            model_name="dispatchitem",
            new_name="dispatch_it_company_53c983_idx",
            old_name="dispatch_ite_company_2a8a3b_idx",
        ),
        migrations.RenameIndex(
            model_name="dispatchorderitem",
            new_name="dispatch_or_company_78c13e_idx",
            old_name="dispatch_ord_company_5d280b_idx",
        ),
    ]
