# Generated by Django 5.0.1 on 2026-02-25 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Dispatch",
            "0009_remove_dispatchplan_dispatch_pl_company_6506fc_idx_and_more",
        ),
        ("Masters", "0028_route_routecoverage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dispatchplan",
            name="route_name",
        ),
        migrations.AddField(
            model_name="dispatchplan",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispatch_plans",
                to="Masters.route",
            ),
        ),
    ]
