# Generated by Django 5.2.16 on 2026-07-14 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('visit_date', models.DateField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('customer_feedback', models.TextField(blank=True, default='')),
                ('remarks', models.TextField(blank=True, default='')),
                ('photos', models.JSONField(blank=True, default=list)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('assigned_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_site_visits', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visits_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date', '-created_on'],
                'indexes': [models.Index(fields=['status'], name='SiteVisit_s_status_961190_idx'), models.Index(fields=['visit_date'], name='SiteVisit_s_visit_d_43bdf7_idx')],
            },
        ),
    ]
