# Generated by Django 5.2.16 on 2026-07-30 12:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Lead', '0001_initial'),
        ('ProjectManagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_todos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sitevisit_calendar_todo',
                'ordering': ['date', 'created_on'],
            },
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_id', models.IntegerField(blank=True, default=None, null=True)),
                ('erp_code', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('modified_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('authorized_level', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('authorized_by_type', models.CharField(blank=True, max_length=30, null=True)),
                ('authorized_by_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('authorized_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('current_authorized_level', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('current_authorized_status', models.SmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1, null=True)),
                ('current_authorized_by_type', models.CharField(blank=True, max_length=30, null=True)),
                ('current_authorized_by_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('current_authorized_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('authorized_status', models.SmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1, null=True)),
                ('customer_name', models.CharField(db_index=True, max_length=200)),
                ('project_name', models.CharField(blank=True, help_text='Denormalized project name for display', max_length=200, null=True)),
                ('visit_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=20)),
                ('customer_feedback', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='assigned_site_visits', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, help_text='Linked lead (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='Lead.lead')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='site_visits', to='ProjectManagement.project')),
            ],
            options={
                'db_table': 'Lead_sitevisit',
                'ordering': ['-visit_date', '-created_on'],
                'permissions': [('export_sitevisit', 'Can export site visits')],
            },
        ),
        migrations.CreateModel(
            name='SiteVisitPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='site_visits/photos/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('site_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='SiteVisit.sitevisit')),
            ],
            options={
                'db_table': 'Lead_sitevisitphoto',
                'ordering': ['-uploaded_on'],
            },
        ),
    ]
