# Generated by Django 5.2.16 on 2026-07-16 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0003_add_follow_up_time'),
        ('SiteVisit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visits', to='Lead.lead'),
        ),
    ]
