# Generated by Django 5.2.16 on 2026-07-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteVisit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sitevisit',
            table='Lead_sitevisit',
        ),
        migrations.AlterModelTable(
            name='sitevisitphoto',
            table='Lead_sitevisitphoto',
        ),
    ]
