# Generated by Django 5.2.16 on 2026-07-31 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Lead', '0002_initial'),
        ('ProjectManagement', '0001_initial'),
        ('SiteVisit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendartodo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_todos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='assigned_site_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='lead',
            field=models.ForeignKey(blank=True, help_text='Linked lead (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='Lead.lead'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='site_visits', to='ProjectManagement.project'),
        ),
        migrations.AddField(
            model_name='sitevisitphoto',
            name='site_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='SiteVisit.sitevisit'),
        ),
    ]
