# Generated by Django 5.2.16 on 2026-08-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteVisit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisit',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=20),
        ),
    ]
