# Generated by Django 5.2.16 on 2026-07-20 06:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_phase1_new_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('BOOKED', 'Booked'), ('AGREEMENT', 'Agreement'), ('REGISTERED', 'Registered'), ('CANCELLED', 'Cancelled')], max_length=15, null=True)),
                ('to_status', models.CharField(choices=[('BOOKED', 'Booked'), ('AGREEMENT', 'Agreement'), ('REGISTERED', 'Registered'), ('CANCELLED', 'Cancelled')], max_length=15)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('changed_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-changed_on'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_id', models.IntegerField(blank=True, default=None, null=True)),
                ('erp_code', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('modified_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('authorized_level', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('authorized_by_type', models.CharField(blank=True, max_length=30, null=True)),
                ('authorized_by_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('authorized_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('current_authorized_level', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('current_authorized_status', models.SmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1, null=True)),
                ('current_authorized_by_type', models.CharField(blank=True, max_length=30, null=True)),
                ('current_authorized_by_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('current_authorized_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('authorized_status', models.SmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1, null=True)),
                ('customer_name', models.CharField(db_index=True, max_length=200)),
                ('customer_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('unit_type', models.CharField(choices=[('PLOT', 'Plot'), ('FLAT', 'Flat / Unit')], default='PLOT', max_length=10)),
                ('unit_number', models.CharField(blank=True, help_text='Denormalised unit number for quick display', max_length=50, null=True)),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('booking_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('booking_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('AGREEMENT', 'Agreement'), ('REGISTERED', 'Registered'), ('CANCELLED', 'Cancelled')], db_index=True, default='BOOKED', max_length=15)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('cancelled_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('flat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='Inventory.flatinventory')),
            ],
            options={
                'ordering': ['-booking_date', '-created_on'],
                'permissions': [('export_booking', 'Can export bookings')],
            },
        ),
    ]
