# Generated by Django 5.2.16 on 2026-07-20 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Booking', '0001_initial'),
        ('Inventory', '0001_phase1_new_modules'),
        ('Lead', '0001_initial'),
        ('Masters', '0045_change_project_location_to_charfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lead',
            field=models.ForeignKey(blank=True, help_text='Linked lead (customer)', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='Lead.lead'),
        ),
        migrations.AddField(
            model_name='booking',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='Inventory.plotinventory'),
        ),
        migrations.AddField(
            model_name='booking',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='Masters.project'),
        ),
        migrations.AddField(
            model_name='booking',
            name='sales_executive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bookings_as_executive', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingstatushistory',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='Booking.booking'),
        ),
        migrations.AddField(
            model_name='bookingstatushistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
