# Generated by Django 5.2.16 on 2026-07-31 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Booking', '0001_initial'),
        ('Inventory', '0001_initial'),
        ('Lead', '0001_initial'),
        ('ProjectManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lead',
            field=models.ForeignKey(blank=True, help_text='Linked lead (customer)', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='Lead.lead'),
        ),
        migrations.AddField(
            model_name='booking',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='Inventory.plotinventory'),
        ),
        migrations.AddField(
            model_name='booking',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='ProjectManagement.project'),
        ),
    ]
