# Generated by Django 5.2.16 on 2026-08-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='incentive',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Incentive/commission for sales executive', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='property_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total property cost', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Revenue from this booking', max_digits=14, null=True),
        ),
    ]
