# Generated by Django 5.2.16 on 2026-07-14 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Masters', '0043_project_projectstatushistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.CharField(max_length=50, unique=True)),
                ('area', models.DecimalField(decimal_places=2, help_text='Area in sq.ft', max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BLOCKED', 'Blocked'), ('BOOKED', 'Booked'), ('REGISTERED', 'Registered')], default='AVAILABLE', max_length=20)),
                ('facing', models.CharField(blank=True, default='', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plots', to='Masters.project')),
            ],
            options={
                'ordering': ['project', 'plot_number'],
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tower', models.CharField(max_length=50)),
                ('floor', models.IntegerField()),
                ('unit_number', models.CharField(max_length=50)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('facing', models.CharField(blank=True, default='', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BLOCKED', 'Blocked'), ('BOOKED', 'Booked'), ('REGISTERED', 'Registered')], default='AVAILABLE', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flats', to='Masters.project')),
            ],
            options={
                'ordering': ['project', 'tower', 'floor', 'unit_number'],
                'unique_together': {('project', 'tower', 'floor', 'unit_number')},
            },
        ),
    ]
