# Generated by Django 5.2.16 on 2026-07-17 18:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Masters", "0043_project_projectstatushistory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlatInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("erp_id", models.IntegerField(blank=True, default=None, null=True)),
                ("erp_code", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "created_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "created_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "modified_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("modified_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "is_deleted",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "authorized_level",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "authorized_by_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "authorized_by_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("authorized_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "current_authorized_level",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "current_authorized_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")],
                        default=1,
                        null=True,
                    ),
                ),
                (
                    "current_authorized_by_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "current_authorized_by_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_authorized_on",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "authorized_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")],
                        default=1,
                        null=True,
                    ),
                ),
                (
                    "tower",
                    models.CharField(
                        blank=True,
                        help_text='Tower / Block name, e.g. "Tower A"',
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "floor",
                    models.PositiveIntegerField(
                        blank=True, help_text="Floor number (0 = Ground)", null=True
                    ),
                ),
                (
                    "unit_number",
                    models.CharField(
                        db_index=True,
                        help_text='Unit/Flat number, e.g. "101", "A-203"',
                        max_length=50,
                    ),
                ),
                (
                    "flat_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 2BHK, 3BHK, Studio",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "area_sqft",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Built-up area in sq ft",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "carpet_area_sqft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "facing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EAST", "East"),
                            ("WEST", "West"),
                            ("NORTH", "North"),
                            ("SOUTH", "South"),
                            ("NE", "North East"),
                            ("NW", "North West"),
                            ("SE", "South East"),
                            ("SW", "South West"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total sale price",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("BLOCKED", "Blocked"),
                            ("BOOKED", "Booked"),
                            ("REGISTERED", "Registered"),
                        ],
                        db_index=True,
                        default="AVAILABLE",
                        max_length=15,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flats",
                        to="Masters.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flat / Unit",
                "verbose_name_plural": "Flats / Units",
                "ordering": ["project", "tower", "floor", "unit_number"],
                "permissions": [("export_flatinventory", "Can export flats")],
                "unique_together": {("project", "tower", "unit_number")},
            },
        ),
        migrations.CreateModel(
            name="PlotInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("erp_id", models.IntegerField(blank=True, default=None, null=True)),
                ("erp_code", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "created_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "created_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "modified_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("modified_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "is_deleted",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "authorized_level",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "authorized_by_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "authorized_by_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("authorized_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "current_authorized_level",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "current_authorized_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")],
                        default=1,
                        null=True,
                    ),
                ),
                (
                    "current_authorized_by_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "current_authorized_by_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_authorized_on",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "authorized_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")],
                        default=1,
                        null=True,
                    ),
                ),
                ("plot_number", models.CharField(db_index=True, max_length=50)),
                (
                    "area_sqyd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Area in square yards",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "area_sqft",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Area in square feet",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "facing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EAST", "East"),
                            ("WEST", "West"),
                            ("NORTH", "North"),
                            ("SOUTH", "South"),
                            ("NE", "North East"),
                            ("NW", "North West"),
                            ("SE", "South East"),
                            ("SW", "South West"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "road_width",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "30 feet", "40 feet"',
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "price_per_sqyd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("BLOCKED", "Blocked"),
                            ("BOOKED", "Booked"),
                            ("REGISTERED", "Registered"),
                        ],
                        db_index=True,
                        default="AVAILABLE",
                        max_length=15,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plots",
                        to="Masters.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plot",
                "verbose_name_plural": "Plots",
                "ordering": ["project", "plot_number"],
                "permissions": [("export_plotinventory", "Can export plots")],
                "unique_together": {("project", "plot_number")},
            },
        ),
    ]
