# Generated by Django 5.2.16 on 2026-07-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_scoped_item_enforcement', models.BooleanField(default=False, help_text='When enabled, item must belong to selected company in sales flows')),
                ('allow_multiple_schemes', models.BooleanField(default=True, help_text='When disabled, only one scheme can be selected per sales order')),
                ('enable_email_notifications', models.BooleanField(default=True, help_text='Enable sending email notifications system-wide')),
                ('enable_push_notifications', models.BooleanField(default=True, help_text='Enable push notifications via Firebase')),
                ('notify_manager_on_booking', models.BooleanField(default=True, help_text='Send notification to reporting manager when a new booking is created')),
                ('notify_employee_on_lead_assignment', models.BooleanField(default=True, help_text='Send notification to employee when a lead is assigned to them')),
                ('company_name', models.CharField(default='Royal Reality Groups', help_text='Company name displayed in the application', max_length=200)),
                ('company_logo', models.ImageField(blank=True, help_text='Company logo (recommended 200x60px)', null=True, upload_to='settings/')),
                ('date_format', models.CharField(default='DD-MM-YYYY', help_text='Date display format (DD-MM-YYYY, MM-DD-YYYY, YYYY-MM-DD)', max_length=20)),
                ('currency_symbol', models.CharField(default='₹', help_text='Currency symbol used in reports and display', max_length=10)),
                ('pagination_size', models.PositiveIntegerField(default=20, help_text='Default number of records per page')),
                ('session_timeout', models.PositiveIntegerField(default=60, help_text='Session timeout in minutes (0 = no timeout)')),
                ('force_password_reset_on_first_login', models.BooleanField(default=True, help_text='Require users to change password on their first login')),
                ('password_expiry_days', models.PositiveIntegerField(default=0, help_text='Force password change after N days (0 = never expires)')),
                ('max_login_attempts', models.PositiveIntegerField(default=5, help_text='Lock account after N failed login attempts (0 = unlimited)')),
            ],
            options={
                'verbose_name': 'General Settings',
                'verbose_name_plural': 'General Settings',
            },
        ),
        migrations.CreateModel(
            name='ImportPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Import Permission',
                'verbose_name_plural': 'Import Permissions',
                'permissions': [('view_import_data', 'Can view import data'), ('view_import_history', 'Can view import history'), ('view_general_settings', 'Can view general settings'), ('modify_general_settings', 'Can modify general settings')],
                'default_permissions': (),
            },
        ),
    ]
