# Generated by Django 4.2.6 on 2026-01-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import Permission",
                "verbose_name_plural": "Import Permissions",
                "permissions": [
                    ("view_import_data", "Can view import data"),
                    ("view_import_history", "Can view import history"),
                ],
                "default_permissions": (),
            },
        ),
    ]
