# Generated by Django 5.2.16 on 2026-08-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("General", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsettings",
            name="fcm_android_app_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Firebase Android App ID (from google-services.json → mobilesdk_app_id)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="fcm_api_key",
            field=models.CharField(
                blank=True, default="", help_text="Firebase Web API Key", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="fcm_auth_domain",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Firebase Auth Domain (e.g., "project-id.firebaseapp.com")',
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="fcm_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable Firebase Cloud Messaging push notifications",
            ),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="fcm_ios_app_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Firebase iOS App ID (from GoogleService-Info.plist → GOOGLE_APP_ID)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="fcm_project_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Firebase Project ID (e.g., "my-project-12345")',
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="fcm_sender_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Firebase Cloud Messaging Sender ID",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="fcm_service_account_json",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Firebase service account JSON (from Firebase Console → Project Settings → Service Accounts)",
            ),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="fcm_storage_bucket",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Firebase Storage Bucket URL (optional)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="fcm_vapid_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="VAPID Key for Web Push (Firebase Console → Cloud Messaging → Web Push certificates)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="fcm_web_app_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Firebase Web App ID (from Firebase Console → Project Settings → Your apps)",
                max_length=200,
            ),
        ),
    ]
