# Generated by Django 4.2.6 on 2026-03-06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("General", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="importpermission",
            options={
                "default_permissions": (),
                "permissions": [
                    ("view_import_data", "Can view import data"),
                    ("view_import_history", "Can view import history"),
                    ("view_general_settings", "Can view general settings"),
                ],
                "verbose_name": "Import Permission",
                "verbose_name_plural": "Import Permissions",
            },
        ),
    ]

