# Generated by Django 4.2.6 on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("General", "0002_add_general_settings_permission"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_scoped_item_enforcement",
                    models.BooleanField(
                        default=False,
                        help_text="When enabled, item must belong to selected company in sales flows",
                    ),
                ),
                (
                    "allow_multiple_schemes",
                    models.BooleanField(
                        default=True,
                        help_text="When disabled, only one scheme can be selected per sales order",
                    ),
                ),
            ],
            options={
                "verbose_name": "General Settings",
                "verbose_name_plural": "General Settings",
            },
        ),
    ]

