# Generated by Django 5.2.16 on 2026-07-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0004_add_modify_general_settings_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Company logo (recommended 200x60px)', null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='company_name',
            field=models.CharField(default='Royal Reality Groups', help_text='Company name displayed in the application', max_length=200),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='currency_symbol',
            field=models.CharField(default='₹', help_text='Currency symbol used in reports and display', max_length=10),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='date_format',
            field=models.CharField(default='DD-MM-YYYY', help_text='Date display format (DD-MM-YYYY, MM-DD-YYYY, YYYY-MM-DD)', max_length=20),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='enable_email_notifications',
            field=models.BooleanField(default=True, help_text='Enable sending email notifications system-wide'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='enable_push_notifications',
            field=models.BooleanField(default=True, help_text='Enable push notifications via Firebase'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='force_password_reset_on_first_login',
            field=models.BooleanField(default=True, help_text='Require users to change password on their first login'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='max_login_attempts',
            field=models.PositiveIntegerField(default=5, help_text='Lock account after N failed login attempts (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='notify_employee_on_lead_assignment',
            field=models.BooleanField(default=True, help_text='Send notification to employee when a lead is assigned to them'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='notify_manager_on_booking',
            field=models.BooleanField(default=True, help_text='Send notification to reporting manager when a new booking is created'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='pagination_size',
            field=models.PositiveIntegerField(default=20, help_text='Default number of records per page'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='password_expiry_days',
            field=models.PositiveIntegerField(default=0, help_text='Force password change after N days (0 = never expires)'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='session_timeout',
            field=models.PositiveIntegerField(default=60, help_text='Session timeout in minutes (0 = no timeout)'),
        ),
    ]
