# Generated by Django 5.2.16 on 2026-07-20 06:15

import Documents.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_id', models.IntegerField(blank=True, default=None, null=True)),
                ('erp_code', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('modified_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('authorized_level', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('authorized_by_type', models.CharField(blank=True, max_length=30, null=True)),
                ('authorized_by_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('authorized_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('current_authorized_level', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('current_authorized_status', models.SmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1, null=True)),
                ('current_authorized_by_type', models.CharField(blank=True, max_length=30, null=True)),
                ('current_authorized_by_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('current_authorized_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('authorized_status', models.SmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1, null=True)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('document_type', models.CharField(choices=[('BROCHURE', 'Brochure'), ('LAYOUT_PLAN', 'Layout Plan'), ('FLOOR_PLAN', 'Floor Plan'), ('APPROVAL_DOC', 'Approval Document'), ('CUSTOMER_KYC', 'Customer KYC'), ('BOOKING_FORM', 'Booking Form'), ('AGREEMENT', 'Agreement'), ('PHOTO', 'Photo'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(help_text='Supported: PDF, JPG, PNG, XLSX', upload_to=Documents.models.document_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('linked_to', models.CharField(choices=[('PROJECT', 'Project'), ('LEAD', 'Lead'), ('BOOKING', 'Booking')], default='PROJECT', max_length=10)),
                ('is_public', models.BooleanField(default=False, help_text='Public documents are visible on the customer website')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Booking.booking')),
            ],
            options={
                'ordering': ['-created_on'],
                'permissions': [('export_document', 'Can export documents')],
            },
        ),
    ]
