# Generated by Django 5.2.16 on 2026-07-31 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Documents', '0001_initial'),
        ('Lead', '0001_initial'),
        ('ProjectManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Lead.lead'),
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ProjectManagement.project'),
        ),
    ]
