# Generated by Django 5.0.1 on 2026-01-30 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Masters", "0003_remove_distributor_distributor_state_active_idx_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core_users", "0002_alter_authorizationhistory_authorized_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorization",
            name="authorization_definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="level_authorizations",
                to="core_users.authorizationdefinition",
            ),
        ),
        migrations.AddField(
            model_name="authorizationdefinition",
            name="authorization_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="authorizationdefinition",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="authorization_definitions",
                to="Masters.company",
            ),
        ),
        migrations.AddField(
            model_name="authorizationdefinition",
            name="effective_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="authorizationdefinition",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="authorization_definitions",
                to="Masters.location",
            ),
        ),
        migrations.AddField(
            model_name="authorizationdefinition",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name="authorizationdefinition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", True)),
                fields=("company", "location", "screen"),
                name="unique_active_authorization_definition",
            ),
        ),
    ]
