# Generated by Django 4.2.6 on 2026-02-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Masters", "0007_distributor_mobile_2_retailer_mobile_2_and_more"),
        ("core_users", "0003_authorization_authorization_definition_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="authorizationdefinition",
            name="unique_active_authorization_definition",
        ),
        migrations.RemoveField(
            model_name="authorizationdefinition",
            name="company",
        ),
        migrations.RemoveField(
            model_name="authorizationdefinition",
            name="location",
        ),
        migrations.AddField(
            model_name="authorizationdefinition",
            name="companies",
            field=models.ManyToManyField(
                blank=True,
                related_name="authorization_definitions",
                to="Masters.company",
            ),
        ),
        migrations.AddField(
            model_name="authorizationdefinition",
            name="has_all_companies",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="authorizationdefinition",
            name="has_all_locations",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="authorizationdefinition",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                related_name="authorization_definitions",
                to="Masters.location",
            ),
        ),
        migrations.AddConstraint(
            model_name="authorizationdefinition",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("has_all_companies", True),
                    ("has_all_locations", True),
                    ("status", True),
                ),
                fields=("screen",),
                name="unique_active_global_authorization",
            ),
        ),
    ]
