# Generated by Django 5.2.16 on 2026-07-31 08:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_id', models.IntegerField(blank=True, default=None, null=True)),
                ('erp_code', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('modified_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('authorized_level', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('authorized_by_type', models.CharField(blank=True, max_length=30, null=True)),
                ('authorized_by_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('authorized_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('current_authorized_level', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('current_authorized_status', models.SmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1, null=True)),
                ('current_authorized_by_type', models.CharField(blank=True, max_length=30, null=True)),
                ('current_authorized_by_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('current_authorized_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('authorized_status', models.SmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1, null=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('developer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('project_type', models.CharField(choices=[('PLOT', 'Plot'), ('FLAT', 'Flat'), ('VILLA', 'Villa'), ('MIXED', 'Mixed')], db_index=True, default='PLOT', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Project location (free text)', max_length=255, null=True)),
                ('approval_type', models.CharField(choices=[('GVMC', 'GVMC'), ('VMRDA', 'VMRDA'), ('DTCP', 'DTCP'), ('HMDA', 'HMDA'), ('PANCHAYAT', 'Panchayat'), ('PENDING', 'Pending'), ('NA', 'N/A')], default='PENDING', max_length=20)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('SOLD_OUT', 'Sold Out')], db_index=True, default='UPCOMING', max_length=20)),
                ('sub', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('overview', models.TextField(blank=True, help_text='Brief project overview (shown in cards/previews)', null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed project description', null=True)),
                ('amenities', models.TextField(blank=True, help_text='List of amenities (can be JSON or comma-separated)', null=True)),
                ('specifications', models.TextField(blank=True, help_text='Project specifications (can be JSON or structured text)', null=True)),
                ('floor_plans_text', models.TextField(blank=True, help_text='Floor plan details as text description', null=True)),
                ('elevation_image', models.ImageField(blank=True, help_text='Main elevation image for project preview', null=True, upload_to='projects/elevation/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail image for cards/lists', null=True, upload_to='projects/thumbnails/')),
                ('floor_plans', models.JSONField(blank=True, default=list, help_text='List of floor plan image URLs')),
                ('gallery', models.JSONField(blank=True, default=list, help_text='List of gallery image URLs')),
                ('brochure', models.FileField(blank=True, help_text='Project brochure PDF', null=True, upload_to='projects/brochures/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['name'],
                'permissions': [('export_project', 'Can export projects')],
                'indexes': [models.Index(fields=['status'], name='ProjectMana_status_f24e31_idx'), models.Index(fields=['project_type'], name='ProjectMana_project_c6b153_idx'), models.Index(fields=['is_active'], name='ProjectMana_is_acti_5a7ffa_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_id', models.IntegerField(blank=True, default=None, null=True)),
                ('erp_code', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('modified_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(upload_to='projects/images/')),
                ('image_type', models.CharField(choices=[('GALLERY', 'Gallery'), ('FLOOR_PLAN', 'Floor Plan'), ('ELEVATION', 'Elevation')], default='GALLERY', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ProjectManagement.project')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
                'ordering': ['order', 'created_on'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_id', models.IntegerField(blank=True, default=None, null=True)),
                ('erp_code', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('modified_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('from_status', models.CharField(blank=True, choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('SOLD_OUT', 'Sold Out')], max_length=20, null=True)),
                ('to_status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('SOLD_OUT', 'Sold Out')], max_length=20)),
                ('changed_by_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='ProjectManagement.project')),
            ],
            options={
                'verbose_name': 'Project Status History',
                'verbose_name_plural': 'Project Status History',
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['project', '-created_on'], name='ProjectMana_project_a0279e_idx')],
            },
        ),
    ]
