# Generated by Django 5.2.17 on 2026-08-30 11:42

from django.db import migrations, models


# Map legacy choice values onto the new, narrowed choice set so existing rows
# stay valid and render correctly in the UI dropdowns.
STATUS_MAP = {
    'UPCOMING': 'UNDER_CONSTRUCTION',
    'ACTIVE': 'UNDER_CONSTRUCTION',
    'COMPLETED': 'READY_TO_OCCUPY',
    'SOLD_OUT': 'READY_TO_OCCUPY',
}
APPROVAL_MAP = {
    'DTCP': 'VMRDA',
    'HMDA': 'GVMC',
    'PANCHAYAT': 'GVMC',
    'PENDING': 'GVMC',
    'NA': 'GVMC',
}


def remap_legacy_values(apps, schema_editor):
    Project = apps.get_model('ProjectManagement', 'Project')
    for old, new in STATUS_MAP.items():
        Project.objects.filter(status=old).update(status=new)
    for old, new in APPROVAL_MAP.items():
        Project.objects.filter(approval_type=old).update(approval_type=new)

    ProjectStatusHistory = apps.get_model('ProjectManagement', 'ProjectStatusHistory')
    for old, new in STATUS_MAP.items():
        ProjectStatusHistory.objects.filter(from_status=old).update(from_status=new)
        ProjectStatusHistory.objects.filter(to_status=old).update(to_status=new)


def noop_reverse(apps, schema_editor):
    # Legacy values are not restored on reverse (mapping is lossy).
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagement', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remap_legacy_values, noop_reverse),
        migrations.AlterField(
            model_name='project',
            name='approval_type',
            field=models.CharField(choices=[('GVMC', 'GVMC'), ('VMRDA', 'VMRDA'), ('RERA', 'RERA')], default='GVMC', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('UNDER_CONSTRUCTION', 'Under Construction'), ('READY_TO_OCCUPY', 'Ready to Occupy')], db_index=True, default='UNDER_CONSTRUCTION', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectstatushistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('UNDER_CONSTRUCTION', 'Under Construction'), ('READY_TO_OCCUPY', 'Ready to Occupy')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projectstatushistory',
            name='to_status',
            field=models.CharField(choices=[('UNDER_CONSTRUCTION', 'Under Construction'), ('READY_TO_OCCUPY', 'Ready to Occupy')], max_length=20),
        ),
    ]
