# Generated by Django 5.2.16 on 2026-07-20 06:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Masters', '0045_change_project_location_to_charfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_id', models.IntegerField(blank=True, default=None, null=True)),
                ('erp_code', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('modified_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('authorized_level', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('authorized_by_type', models.CharField(blank=True, max_length=30, null=True)),
                ('authorized_by_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('authorized_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('current_authorized_level', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('current_authorized_status', models.SmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1, null=True)),
                ('current_authorized_by_type', models.CharField(blank=True, max_length=30, null=True)),
                ('current_authorized_by_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('current_authorized_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('authorized_status', models.SmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1, null=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('mobile', models.CharField(db_index=True, max_length=15)),
                ('alternate_number', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('budget', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_area', models.CharField(blank=True, max_length=200, null=True)),
                ('property_requirement', models.CharField(blank=True, max_length=200, null=True)),
                ('lead_source', models.CharField(choices=[('WEBSITE', 'Website'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('GOOGLE_ADS', 'Google Ads'), ('WHATSAPP', 'WhatsApp'), ('MAGICBRICKS', 'MagicBricks'), ('99ACRES', '99acres'), ('REFERRALS', 'Referrals'), ('MANUAL', 'Manual Entry')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('NEW_LEAD', 'New Lead'), ('CONTACT_ATTEMPTED', 'Contact Attempted'), ('CONNECTED', 'Connected'), ('INTERESTED', 'Interested'), ('SITE_VISIT_SCHEDULED', 'Site Visit Scheduled'), ('SITE_VISIT_COMPLETED', 'Site Visit Completed'), ('NEGOTIATION', 'Negotiation'), ('BOOKING', 'Booking'), ('REGISTRATION', 'Registration'), ('LOST', 'Lost')], db_index=True, default='NEW_LEAD', max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('cross_lead_override', models.BooleanField(default=False)),
                ('cross_lead_override_reason', models.TextField(blank=True, null=True)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('interested_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_leads', to='Masters.project')),
            ],
            options={
                'ordering': ['-created_on'],
                'permissions': [('export_lead', 'Can export leads')],
            },
        ),
        migrations.CreateModel(
            name='LeadCrossCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_field', models.CharField(max_length=50)),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicates_found', to='Lead.lead')),
                ('original_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_checks', to='Lead.lead')),
            ],
        ),
        migrations.CreateModel(
            name='LeadFollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_id', models.IntegerField(blank=True, default=None, null=True)),
                ('erp_code', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('modified_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('authorized_level', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('authorized_by_type', models.CharField(blank=True, max_length=30, null=True)),
                ('authorized_by_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('authorized_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('current_authorized_level', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('current_authorized_status', models.SmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1, null=True)),
                ('current_authorized_by_type', models.CharField(blank=True, max_length=30, null=True)),
                ('current_authorized_by_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('current_authorized_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('authorized_status', models.SmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1, null=True)),
                ('follow_up_date', models.DateField(db_index=True)),
                ('follow_up_type', models.CharField(choices=[('CALL', 'Call'), ('WHATSAPP', 'WhatsApp'), ('MEETING', 'Meeting'), ('SITE_VISIT', 'Site Visit')], max_length=20)),
                ('discussion_notes', models.TextField(blank=True, null=True)),
                ('follow_up_time', models.TimeField(blank=True, null=True)),
                ('next_follow_up_date', models.DateField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lead_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='Lead.lead')),
            ],
            options={
                'ordering': ['-follow_up_date'],
            },
        ),
        migrations.CreateModel(
            name='LeadStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_id', models.IntegerField(blank=True, default=None, null=True)),
                ('erp_code', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('modified_by_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('authorized_level', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('authorized_by_type', models.CharField(blank=True, max_length=30, null=True)),
                ('authorized_by_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('authorized_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('current_authorized_level', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('current_authorized_status', models.SmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1, null=True)),
                ('current_authorized_by_type', models.CharField(blank=True, max_length=30, null=True)),
                ('current_authorized_by_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('current_authorized_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('authorized_status', models.SmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1, null=True)),
                ('from_status', models.CharField(blank=True, choices=[('NEW_LEAD', 'New Lead'), ('CONTACT_ATTEMPTED', 'Contact Attempted'), ('CONNECTED', 'Connected'), ('INTERESTED', 'Interested'), ('SITE_VISIT_SCHEDULED', 'Site Visit Scheduled'), ('SITE_VISIT_COMPLETED', 'Site Visit Completed'), ('NEGOTIATION', 'Negotiation'), ('BOOKING', 'Booking'), ('REGISTRATION', 'Registration'), ('LOST', 'Lost')], max_length=30, null=True)),
                ('to_status', models.CharField(choices=[('NEW_LEAD', 'New Lead'), ('CONTACT_ATTEMPTED', 'Contact Attempted'), ('CONNECTED', 'Connected'), ('INTERESTED', 'Interested'), ('SITE_VISIT_SCHEDULED', 'Site Visit Scheduled'), ('SITE_VISIT_COMPLETED', 'Site Visit Completed'), ('NEGOTIATION', 'Negotiation'), ('BOOKING', 'Booking'), ('REGISTRATION', 'Registration'), ('LOST', 'Lost')], max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lead_status_changes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='Lead.lead')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['mobile', 'alternate_number', 'email'], name='Lead_lead_mobile_685386_idx'),
        ),
    ]
