# Generated by Django 5.2.16 on 2026-07-31 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Lead', '0001_initial'),
        ('ProjectManagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='interested_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_leads', to='ProjectManagement.project'),
        ),
        migrations.AddField(
            model_name='leadcrosscheck',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadcrosscheck',
            name='duplicate_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicates_found', to='Lead.lead'),
        ),
        migrations.AddField(
            model_name='leadcrosscheck',
            name='original_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_checks', to='Lead.lead'),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lead_follow_ups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='Lead.lead'),
        ),
        migrations.AddField(
            model_name='leadstatushistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lead_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadstatushistory',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='Lead.lead'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['mobile', 'alternate_number', 'email'], name='Lead_lead_mobile_685386_idx'),
        ),
    ]
