# Generated by Django 5.2.16 on 2026-07-11 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_on'], 'permissions': [('export_lead', 'Can export leads')]},
        ),
    ]
