# Generated by Django 5.2.16 on 2026-07-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0002_alter_lead_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadfollowup',
            name='follow_up_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
