# Generated by Django 5.2.16 on 2026-07-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW_LEAD', 'New Lead'), ('CONTACT_ATTEMPTED', 'Contact Attempted'), ('CONNECTED', 'Connected'), ('PROSPECT', 'Prospect'), ('INTERESTED', 'Interested'), ('HOT_LEAD', 'Hot Lead'), ('SITE_VISIT_SCHEDULED', 'Site Visit Scheduled'), ('SITE_VISIT_COMPLETED', 'Site Visit Completed'), ('NEGOTIATION', 'Negotiation'), ('BOOKING', 'Booking'), ('REGISTRATION', 'Registration'), ('LOST', 'Lost')], db_index=True, default='NEW_LEAD', max_length=30),
        ),
        migrations.AlterField(
            model_name='leadstatushistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('NEW_LEAD', 'New Lead'), ('CONTACT_ATTEMPTED', 'Contact Attempted'), ('CONNECTED', 'Connected'), ('PROSPECT', 'Prospect'), ('INTERESTED', 'Interested'), ('HOT_LEAD', 'Hot Lead'), ('SITE_VISIT_SCHEDULED', 'Site Visit Scheduled'), ('SITE_VISIT_COMPLETED', 'Site Visit Completed'), ('NEGOTIATION', 'Negotiation'), ('BOOKING', 'Booking'), ('REGISTRATION', 'Registration'), ('LOST', 'Lost')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='leadstatushistory',
            name='to_status',
            field=models.CharField(choices=[('NEW_LEAD', 'New Lead'), ('CONTACT_ATTEMPTED', 'Contact Attempted'), ('CONNECTED', 'Connected'), ('PROSPECT', 'Prospect'), ('INTERESTED', 'Interested'), ('HOT_LEAD', 'Hot Lead'), ('SITE_VISIT_SCHEDULED', 'Site Visit Scheduled'), ('SITE_VISIT_COMPLETED', 'Site Visit Completed'), ('NEGOTIATION', 'Negotiation'), ('BOOKING', 'Booking'), ('REGISTRATION', 'Registration'), ('LOST', 'Lost')], max_length=30),
        ),
    ]
