# Generated by Django 5.2.16 on 2026-08-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0003_alter_lead_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='bucket',
            field=models.CharField(blank=True, choices=[('NEW_LEAD', 'New Lead'), ('HOT_LEAD', 'Hot Lead'), ('PROSPECTS', 'Prospects')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('ONGOING', 'Ongoing'), ('LIVE', 'Live'), ('DEAD', 'Dead')], db_index=True, default='ONGOING', max_length=30),
        ),
        migrations.AlterField(
            model_name='leadstatushistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('ONGOING', 'Ongoing'), ('LIVE', 'Live'), ('DEAD', 'Dead')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='leadstatushistory',
            name='to_status',
            field=models.CharField(choices=[('ONGOING', 'Ongoing'), ('LIVE', 'Live'), ('DEAD', 'Dead')], max_length=30),
        ),
    ]
