# Generated by Django 5.2.16 on 2026-07-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0003_add_follow_up_time'),
        ('Lead', '0003_add_site_visit_interested_project'),
    ]

    operations = [
    ]
