# Generated by Django 5.2.16 on 2026-08-03 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0004_lead_bucket_alter_lead_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('call_type', models.CharField(choices=[('outgoing', 'Outgoing'), ('incoming', 'Incoming'), ('missed', 'Missed'), ('rejected', 'Rejected'), ('unknown', 'Unknown')], max_length=10)),
                ('duration_secs', models.PositiveIntegerField(default=0)),
                ('called_at', models.DateTimeField(db_index=True)),
                ('device_platform', models.CharField(default='android', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('called_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='Lead.lead')),
            ],
            options={
                'ordering': ['-called_at'],
                'unique_together': {('phone_number', 'called_at', 'called_by')},
            },
        ),
    ]
