# Generated by Django 5.2.16 on 2026-07-18 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0004_merge_20260718_1552'),
        ('Lead', '0004_merge_20260718_1955'),
    ]

    operations = [
    ]
