# Generated by Django 5.2.17 on 2026-08-11 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0005_calllog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calllog',
            unique_together=set(),
        ),
    ]
