# Generated by Django 5.2.16 on 2026-07-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0005_merge_20260718_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='project_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
