# Generated by Django 5.2.17 on 2026-08-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0006_alter_calllog_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='call_count',
            field=models.PositiveIntegerField(default=1, help_text='How many times this call was synced (same phone+time)'),
        ),
    ]
