# Generated by Django 5.2.17 on 2026-08-11 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0007_calllog_call_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_comments', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, help_text='Auto-matched lead by phone number', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_comments', to='Lead.lead')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('phone_number', 'commented_by')},
            },
        ),
    ]
