# Generated by Django 5.2.17 on 2026-08-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0008_phonecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='call_times',
            field=models.JSONField(blank=True, default=list, help_text='List of all called_at timestamps for this number'),
        ),
    ]
