# Generated by Django 5.2.17 on 2026-08-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0009_calllog_call_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecomment',
            name='comment_history',
            field=models.JSONField(blank=True, default=list, help_text='List of all previous comments with timestamps'),
        ),
    ]
