# Generated by Django 5.2.17 on 2026-08-12 08:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0010_phonecomment_comment_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['phone_number', 'called_by'], name='Lead_calllo_phone_n_b87c81_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['called_at'], name='Lead_calllo_called__7a142d_idx'),
        ),
        migrations.AddIndex(
            model_name='phonecomment',
            index=models.Index(fields=['phone_number', 'commented_by'], name='Lead_phonec_phone_n_6d0445_idx'),
        ),
    ]
