# Generated by Django 5.2.16 on 2026-08-14 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Lead", "0011_calllog_lead_calllo_phone_n_b87c81_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonecomment",
            name="call_log",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked call log — deleted automatically when call log is deleted",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phone_comments",
                to="Lead.calllog",
            ),
        ),
    ]
