# Generated by Django 4.2.6 on 2026-01-23 04:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("erp_id", models.IntegerField(blank=True, default=None, null=True)),
                ("erp_code", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "created_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "created_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "modified_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("modified_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "is_deleted",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "authorized_level",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "authorized_by_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "authorized_by_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("authorized_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "current_authorized_level",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "current_authorized_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Pending"),
                            (2, "Approved"),
                            (3, "Rejected"),
                            (4, "Skipped"),
                        ],
                        default=1,
                        null=True,
                    ),
                ),
                (
                    "current_authorized_by_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "current_authorized_by_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_authorized_on",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "authorized_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Pending"),
                            (2, "Approved"),
                            (3, "Rejected"),
                            (4, "Skipped"),
                        ],
                        default=4,
                        null=True,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("invoice_date", models.DateField(db_index=True)),
                ("due_date", models.DateField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("DISPATCH", "From Dispatch Plan"),
                            ("ORDER", "From Sales Order"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("CONFIRMED", "Confirmed"),
                            ("PAID", "Paid"),
                            ("PARTIALLY_PAID", "Partially Paid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "pod_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "POD Pending"),
                            ("COMPLETED", "POD Completed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "taxable_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "freight_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "other_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "round_off",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "balance_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("remarks", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "db_table": "invoice",
                "ordering": ["-invoice_date", "-created_on"],
                "permissions": [("cancel_invoice", "Can cancel invoice")],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("erp_id", models.IntegerField(blank=True, default=None, null=True)),
                ("erp_code", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "created_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "created_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "modified_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("modified_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "is_deleted",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "authorized_level",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "authorized_by_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "authorized_by_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("authorized_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "current_authorized_level",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "current_authorized_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Pending"),
                            (2, "Approved"),
                            (3, "Rejected"),
                            (4, "Skipped"),
                        ],
                        default=1,
                        null=True,
                    ),
                ),
                (
                    "current_authorized_by_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "current_authorized_by_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_authorized_on",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "authorized_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Pending"),
                            (2, "Approved"),
                            (3, "Rejected"),
                            (4, "Skipped"),
                        ],
                        default=4,
                        null=True,
                    ),
                ),
                ("payment_date", models.DateField(db_index=True)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CHEQUE", "Cheque"),
                            ("NEFT", "NEFT"),
                            ("RTGS", "RTGS"),
                            ("UPI", "UPI"),
                            ("CARD", "Card"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("remarks", models.TextField(blank=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="Invoice.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "db_table": "payment",
                "ordering": ["-payment_date", "-created_on"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("erp_id", models.IntegerField(blank=True, default=None, null=True)),
                ("erp_code", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "created_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "created_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "modified_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("modified_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "is_deleted",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "authorized_level",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "authorized_by_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "authorized_by_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("authorized_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "current_authorized_level",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "current_authorized_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Pending"),
                            (2, "Approved"),
                            (3, "Rejected"),
                            (4, "Skipped"),
                        ],
                        default=1,
                        null=True,
                    ),
                ),
                (
                    "current_authorized_by_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "current_authorized_by_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_authorized_on",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "authorized_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Pending"),
                            (2, "Approved"),
                            (3, "Rejected"),
                            (4, "Skipped"),
                        ],
                        default=4,
                        null=True,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "taxable_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "cgst_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "cgst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "sgst_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "igst_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "igst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "cess_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "cess_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "line_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="Invoice.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Item",
                "verbose_name_plural": "Invoice Items",
                "db_table": "invoice_item",
                "ordering": ["created_on"],
            },
        ),
    ]
