# Generated by Django 4.2.6 on 2026-01-23 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Sales", "0001_initial"),
        ("Masters", "0001_initial"),
        ("Dispatch", "0002_initial"),
        ("Invoice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="sales_order_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="invoice_items",
                to="Sales.salesorderitem",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="Masters.company",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="dispatch_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="invoices",
                to="Dispatch.dispatchplan",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="Masters.location",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="sales_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="invoices",
                to="Sales.salesorder",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["invoice", "-payment_date"], name="payment_invoice_daf1f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceitem",
            index=models.Index(
                fields=["invoice", "sales_order_item"],
                name="invoice_ite_invoice_518734_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_number"], name="invoice_invoice_5b7137_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_date", "status"], name="invoice_invoice_913e18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["sales_order"], name="invoice_sales_o_1f0b4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["-created_on"], name="invoice_created_05c894_idx"
            ),
        ),
    ]
