# Generated by Django 5.0.1 on 2026-02-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Invoice", "0003_alter_invoice_authorized_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("PAID", "Paid"),
                    ("PARTIALLY_PAID", "Partially Paid"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
