name: RRG-BackEnd-Dev-Deploy

on:
  workflow_run:
    workflows:
      - "RRG-BackEnd-Build"
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: github.event.workflow_run.conclusion == 'success'

    permissions:
      actions: read
      contents: read

    steps:
      - name: Stop Dev Service
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            sudo systemctl stop ${{ secrets.BE_DEV_SERVICE_NAME }}.socket ${{ secrets.BE_DEV_SERVICE_NAME }}.service || true

      - name: Deploy Dev Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -e

            cd "${{ secrets.BE_DEV_TARGET_PATH }}"

            git fetch origin
            git checkout main
            git reset --hard origin/main

            source venv/bin/activate

            pip install -r requirements.txt

            python manage.py collectstatic --noinput
            python manage.py migrate --noinput
            python manage.py UpdateContentTypeDetail
            python manage.py UpdatePermissionDetail
            python manage.py import_menu_data

            sudo systemctl start ${{ secrets.BE_DEV_SERVICE_NAME }}.socket ${{ secrets.BE_DEV_SERVICE_NAME }}.service
