# Generated by Django 4.2.6 on 2026-01-23 04:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Masters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("erp_id", models.IntegerField(blank=True, default=None, null=True)),
                ("erp_code", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "created_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "created_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "modified_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("modified_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "is_deleted",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "authorized_level",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "authorized_by_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "authorized_by_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("authorized_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "current_authorized_level",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "current_authorized_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Pending"),
                            (2, "Approved"),
                            (3, "Rejected"),
                            (4, "Skipped"),
                        ],
                        default=1,
                        null=True,
                    ),
                ),
                (
                    "current_authorized_by_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "current_authorized_by_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_authorized_on",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "authorized_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Pending"),
                            (2, "Approved"),
                            (3, "Rejected"),
                            (4, "Skipped"),
                        ],
                        default=4,
                        null=True,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("order_date", models.DateField(db_index=True)),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("RETAILER", "Retailer"),
                            ("DISTRIBUTOR", "Distributor"),
                            ("SUPERSTOCKIST", "Superstockist"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "credit_days",
                    models.IntegerField(
                        default=0, help_text="Credit days from customer"
                    ),
                ),
                ("billing_address", models.TextField()),
                ("shipping_address", models.TextField()),
                ("same_as_billing", models.BooleanField(default=True)),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("EXCLUSIVE", "Tax Exclusive (Price + Tax)"),
                            ("INCLUSIVE", "Tax Inclusive (Price includes Tax)"),
                        ],
                        default="EXCLUSIVE",
                        help_text="Whether item prices include tax or tax is added separately",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PROCESSING", "Processing"),
                            ("PARTIALLY_INVOICED", "Partially Invoiced"),
                            ("INVOICED", "Invoiced"),
                            ("DELIVERED", "Delivered"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "taxable_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "freight_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "other_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "round_off",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("remarks", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="sales_orders/"),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Sales Order",
                "verbose_name_plural": "Sales Orders",
                "db_table": "sales_order",
                "ordering": ["-order_date", "-created_on"],
            },
        ),
        migrations.CreateModel(
            name="SalesOrderHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("UPDATED", "Updated"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PROCESSING", "Processing Started"),
                            ("INVOICED", "Invoiced"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=20)),
                ("new_status", models.CharField(blank=True, max_length=20)),
                (
                    "changes",
                    models.JSONField(
                        blank=True, help_text="Field changes in JSON format", null=True
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Sales Order History",
                "verbose_name_plural": "Sales Order History",
                "db_table": "sales_order_history",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesOrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("erp_id", models.IntegerField(blank=True, default=None, null=True)),
                ("erp_code", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "created_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "created_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_by_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "modified_by_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("modified_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "is_deleted",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "authorized_level",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "authorized_by_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "authorized_by_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("authorized_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "current_authorized_level",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "current_authorized_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Pending"),
                            (2, "Approved"),
                            (3, "Rejected"),
                            (4, "Skipped"),
                        ],
                        default=1,
                        null=True,
                    ),
                ),
                (
                    "current_authorized_by_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "current_authorized_by_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_authorized_on",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "authorized_status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Pending"),
                            (2, "Approved"),
                            (3, "Rejected"),
                            (4, "Skipped"),
                        ],
                        default=4,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "free_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "pb_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Price Book rate",
                        max_digits=10,
                    ),
                ),
                (
                    "pb_rate_source",
                    models.CharField(
                        blank=True,
                        help_text="Source of PB rate (RETAILER/DISTRIBUTOR/SUPERSTOCKIST/AREA/CITY/STATE/BASE)",
                        max_length=50,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Actual selling rate (editable)",
                        max_digits=10,
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("PERCENTAGE", "Percentage"), ("AMOUNT", "Amount")],
                        default="PERCENTAGE",
                        max_length=10,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "taxable_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "cgst_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "cgst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "sgst_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "igst_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "igst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "cess_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "cess_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "line_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="sales_order_items",
                        to="Masters.item",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="Sales.salesorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Order Item",
                "verbose_name_plural": "Sales Order Items",
                "db_table": "sales_order_item",
                "ordering": ["created_on"],
            },
        ),
    ]
