# Generated by Django 4.2.6 on 2026-01-23 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Sales", "0001_initial"),
        ("Masters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorderhistory",
            name="changed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_order_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salesorderhistory",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="Sales.salesorder",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_sales_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="billing_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="sales_orders_billing",
                to="Masters.area",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="billing_city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="sales_orders_billing",
                to="Masters.city",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="billing_state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="sales_orders_billing",
                to="Masters.state",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_orders",
                to="Masters.company",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="distributor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="sales_orders",
                to="Masters.distributor",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="retailer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="sales_orders",
                to="Masters.retailer",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="shipping_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="sales_orders_shipping",
                to="Masters.area",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="shipping_city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="sales_orders_shipping",
                to="Masters.city",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="shipping_state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="sales_orders_shipping",
                to="Masters.state",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="superstockist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="sales_orders",
                to="Masters.superstockist",
            ),
        ),
        migrations.AddIndex(
            model_name="salesorderitem",
            index=models.Index(
                fields=["order", "item"], name="sales_order_order_i_68883a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorderhistory",
            index=models.Index(
                fields=["order", "-changed_at"], name="sales_order_order_i_69c099_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorderhistory",
            index=models.Index(
                fields=["action", "-changed_at"], name="sales_order_action_e0945c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(
                fields=["order_number"], name="sales_order_order_n_1515f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(
                fields=["order_date", "status"], name="sales_order_order_d_7e6987_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(
                fields=["customer_type", "status"],
                name="sales_order_custome_a36b63_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(
                fields=["-created_on"], name="sales_order_created_2f7aa3_idx"
            ),
        ),
    ]
