# Generated by Django 4.2.6 on 2026-01-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Sales", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorder",
            name="authorized_status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")],
                default=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="current_authorized_status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")],
                default=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="authorized_status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")],
                default=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="current_authorized_status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "Pending"), (2, "Approved"), (3, "Rejected")],
                default=1,
                null=True,
            ),
        ),
    ]
