# Generated by Django 5.0.1 on 2026-01-30 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Sales", "0004_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="salesorder",
            name="salesorder_date_company_idx",
        ),
        migrations.RemoveIndex(
            model_name="salesorder",
            name="salesorder_customer_idx",
        ),
        migrations.RemoveIndex(
            model_name="salesorder",
            name="salesorder_status_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="salesorder",
            name="salesorder_company_status_idx",
        ),
    ]
