# Generated by Django 4.2.6 on 2026-02-03 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Masters", "0007_distributor_mobile_2_retailer_mobile_2_and_more"),
        ("Sales", "0005_remove_salesorder_salesorder_date_company_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorderitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="sales_order_items",
                to="Masters.category",
            ),
        ),
    ]
