# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0006_salesorderitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderAttachment',
            fields=[
                ('id', models.CharField(default='', editable=False, max_length=255, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_by_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_by_type', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_by_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment_type', models.CharField(choices=[('QUOTATION', 'Quotation'), ('PURCHASE_ORDER', 'Purchase Order'), ('DELIVERY_NOTE', 'Delivery Note'), ('INVOICE_COPY', 'Invoice Copy'), ('PAYMENT_RECEIPT', 'Payment Receipt'), ('TRANSPORT_DOCUMENT', 'Transport Document'), ('OTHER', 'Other')], help_text='Type of attachment', max_length=20)),
                ('file', models.FileField(help_text='Attachment file', upload_to='sales_orders/attachments/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, help_text='Original filename', max_length=255, null=True)),
                ('description', models.CharField(blank=True, help_text='Description for attachments', max_length=255, null=True)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='Sales.salesorder')),
            ],
            options={
                'verbose_name': 'Sales Order Attachment',
                'verbose_name_plural': 'Sales Order Attachments',
                'db_table': 'sales_order_attachments',
                'ordering': ['-created_on'],
            },
        ),
        migrations.AddIndex(
            model_name='salesorderattachment',
            index=models.Index(fields=['sales_order', 'attachment_type'], name='sales_order_sales_o_b8b0e4_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderattachment',
            index=models.Index(fields=['attachment_type'], name='sales_order_attachm_2cadf4_idx'),
        ),
    ]
