# Generated by Django 5.0.1 on 2026-02-05 04:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Sales", "0007_salesorderattachment"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="salesorderattachment",
            new_name="sales_order_sales_o_94a94a_idx",
            old_name="sales_order_sales_o_b8b0e4_idx",
        ),
        migrations.RenameIndex(
            model_name="salesorderattachment",
            new_name="sales_order_attachm_bba55e_idx",
            old_name="sales_order_attachm_2cadf4_idx",
        ),
        migrations.AddField(
            model_name="salesorderattachment",
            name="erp_code",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="salesorderattachment",
            name="erp_id",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="salesorderattachment",
            name="created_by_identifier",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="salesorderattachment",
            name="created_by_type",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="salesorderattachment",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="salesorderattachment",
            name="is_deleted",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="salesorderattachment",
            name="modified_by_identifier",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="salesorderattachment",
            name="modified_by_type",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="salesorderattachment",
            name="modified_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
