# Generated by Django 5.0.1 on 2026-02-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Sales",
            "0008_rename_sales_order_sales_o_b8b0e4_idx_sales_order_sales_o_94a94a_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="salesorderattachment",
            name="sales_order_sales_o_94a94a_idx",
        ),
        migrations.RemoveIndex(
            model_name="salesorderattachment",
            name="sales_order_attachm_bba55e_idx",
        ),
        migrations.RemoveField(
            model_name="salesorderattachment",
            name="attachment_type",
        ),
        migrations.AlterField(
            model_name="salesorderattachment",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Description for attachment",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="salesorderattachment",
            index=models.Index(
                fields=["sales_order"], name="sales_order_sales_o_f46f94_idx"
            ),
        ),
    ]
