# Generated by Django 5.0.1 on 2026-02-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Sales",
            "0009_remove_salesorderattachment_sales_order_sales_o_94a94a_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("CONFIRMED", "Confirmed"),
                    ("PARTIALLY_DISPATCHED", "Partially Dispatched"),
                    ("DISPATCHED", "Dispatched"),
                    ("PARTIALLY_INVOICED", "Partially Invoiced"),
                    ("INVOICED", "Invoiced"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
