# Generated by Django 5.0.1 on 2026-02-09 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Masters", "0014_scheme_schemeapplicability_schemebenefit_and_more"),
        ("Sales", "0011_convert_status_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesOrderItemScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Discount amount for this item",
                        max_digits=15,
                    ),
                ),
                (
                    "free_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Free quantity provided for this item",
                        max_digits=10,
                    ),
                ),
                (
                    "sales_order_item",
                    models.ForeignKey(
                        help_text="Sales order item this scheme is applied to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applied_schemes",
                        to="Sales.salesorderitem",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        help_text="Scheme applied to item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applied_order_items",
                        to="Masters.scheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Order Item Scheme",
                "verbose_name_plural": "Sales Order Item Schemes",
                "db_table": "sales_order_item_scheme",
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["sales_order_item", "scheme"],
                        name="sales_order_sales_o_9d517a_idx",
                    )
                ],
                "unique_together": {("sales_order_item", "scheme")},
            },
        ),
        migrations.CreateModel(
            name="SalesOrderScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheme_code",
                    models.CharField(
                        help_text="Scheme code at time of application", max_length=50
                    ),
                ),
                (
                    "scheme_name",
                    models.CharField(
                        help_text="Scheme name at time of application", max_length=255
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total discount amount from this scheme",
                        max_digits=15,
                    ),
                ),
                (
                    "free_items",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Free items provided by this scheme as JSON",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When scheme was applied to order"
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        help_text="Sales order this scheme is applied to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applied_schemes",
                        to="Sales.salesorder",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        help_text="Scheme that was applied",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applied_orders",
                        to="Masters.scheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Order Scheme",
                "verbose_name_plural": "Sales Order Schemes",
                "db_table": "sales_order_scheme",
                "ordering": ["applied_at"],
                "indexes": [
                    models.Index(
                        fields=["sales_order", "scheme"],
                        name="sales_order_sales_o_b9f2e2_idx",
                    )
                ],
                "unique_together": {("sales_order", "scheme")},
            },
        ),
    ]
