# Generated by Django 5.0.1 on 2026-02-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Sales", "0012_salesorderitemscheme_salesorderscheme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("PARTIALLY_DISPATCHED", "Partially Dispatched"),
                    ("DISPATCHED", "Dispatched"),
                    ("PARTIALLY_INVOICED", "Partially Invoiced"),
                    ("INVOICED", "Invoiced"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
