# Generated by Django 4.2.6 on 2026-03-25 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0031_alter_scheme_company'),
        ('Sales', '0013_alter_salesorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_items', to='Masters.company'),
        ),
    ]
