# Generated by Django 5.2.5 on 2026-03-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0014_salesorderitem_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='is_scheme_item',
            field=models.BooleanField(default=False),
        ),
    ]
