# Generated by Django 4.2.6 on 2026-04-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0015_salesorderitem_is_scheme_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderscheme',
            name='free_items',
            field=models.JSONField(blank=True, default=list, help_text='Free items provided by this scheme as JSON'),
        ),
    ]
